### PR TITLE
fix: stop reporting handled jobs-fetch failures as errors

### PR DESCRIPTION
**Pull request by mattmillerai**
## ELI-5

When the app asks the server "what jobs do I have?", that question can fail for boring reasons — you weren't signed in yet, or you closed the tab mid-question. The app already shrugged those off and kept working, but it also shouted "ERROR!" into our monitoring every time, which made real problems hard to find. Now it only shouts when something is actually wrong.

## Summary

The jobs poll already degrades gracefully — on a non-OK status or a thrown fetch it returns an empty result set and the UI carries on — but it logged both paths with `console.error`, so every handled failure was recorded as an error session in RUM. Failures that are ordinary lifecycle events no longer report; genuine faults still do.

## Changes

- **What**: `fetchJobsRaw` now classifies its failures instead of treating them all as errors. A `401` logs at `warn`. A request the browser cancels because the page is being discarded is not logged at all. A `403`, a `5xx`, a body that fails schema validation, and a real network fault all still log at `console.error`. Every path returns the same empty result set as before, so callers and the UI are unchanged.
- **What**: `fetchJobAssets` — added on `main` after this branch was written — gets the same guard, so all four jobs fetchers classify a teardown-cancelled request the same way.
- **What**: a discard is identified from the page lifecycle rather than by pattern-matching the error, because the browser surfaces a teardown-cancelled request as a bare `TypeError: Failed to fetch` that is indistinguishable from a real network fault. `src/utils/pageTeardownUtil.ts` exposes a single predicate, `isPageUnloading()`, backed by a `pagehide`/`pageshow` listener pair. `fetchJobDetail` uses it too. No `AbortController` and no signal is threaded through the fetchers — the browser already cancels in-flight requests when it discards the page, so there was nothing for one to cancel; all that was ever needed was the fact of the discard.
- **What**: the flag is set only on a *non-persisted* `pagehide`. `pagehide` rather than `beforeunload` because `beforeunload` also fires for navigations the user then cancels; and persisted-excluded because a persisted `pagehide` is a back/forward-cache freeze, not a discard — the page resumes and its poll must keep reporting. `pageshow` clears the flag, so a browser that reports a discard for a page it later restores does not leave the fetchers permanently silent.

If teardown somehow cancels a request before `pagehide` fires, the failure is still reported — the fallback direction is "noisier", never "silently swallowed".

## Review Focus

**Why the 401 is not gated, despite being the obvious fix.** The request seam these fetchers are injected with already waits for auth to resolve before every cloud request (`waitForAuthInitialization` in `src/scripts/api.ts`, awaited at the top of `fetchApi`), and a `401` response is already retried once behind a token re-mint (`fetchWithUnifiedRemint`). So the ordering gate the ticket proposed exists; adding a second one in the jobs layer would duplicate it. What still reaches this code is a poll that outran its session — an unauthenticated or expired session, or the 10s auth-initialisation timeout elapsing — which is a lifecycle state, not a defect. Hence `warn` rather than a new gate. The residual timeout case already logs its own warning where it happens.

**The 403 is deliberately still an error.** Reading the server side, a `403` on this endpoint is not raised by the jobs handler at all — it comes from shared request-authorisation middleware, which returns `403` for several unrelated reasons (the credential type not being accepted for the route, an authorisation predicate failing for the account, and an account scheduled for deletion). At least one of those is an expected terminal state and at least one would be a real bug, so the ~79 sessions are almost certainly a mix. The frontend cannot currently separate them because it logs only the status code and discards the response body, which carries a machine-readable error type. Keeping `403` at `console.error` preserves that signal rather than hiding a possible authorisation bug behind this cleanup. Follow-up worth filing separately: surface the response's error type alongside the status so the cluster can be split, then decide whether anything is a real defect. Deliberately not widened here — the server side is out of scope for this change.

**Scope calls.** A failed fetch still returns the same empty result set rather than rethrowing or returning a typed result, so callers cannot distinguish "no jobs" from "cancelled" or from "unauthenticated". Raised in review twice; not changed here. That behaviour is pre-existing — `fetchJobsRaw` already returned an empty page for every non-OK status before this PR — and changing it is a change to the fetch contract that reaches the extension-facing `api.getQueue`/`api.getHistory` and cascades into `queueStore`, `assetsStore` and `missingMediaAssetResolver`, each needing its own guard at the log site or it re-introduces the noise this PR removes. Filed as follow-ups. The other `TypeError: Failed to fetch` sites (remote config, the bare fetch wrapper) are the same pattern at different call sites and are out of scope here; `isPageUnloading()` is written so they can reuse it.

## Verification

`vue-tsc --noEmit` (whole repo), `oxlint --type-aware`, `eslint` (0 errors), `oxfmt` and `knip` all clean. `vitest run` over `src/platform/remote/comfyui/jobs`, `src/platform/workflow/cloud`, `src/platform/missingMedia`, `src/platform/assets`, `src/composables/queue`, `src/stores/queueStore.test.ts`, `src/services/jobOutputCache.test.ts` and `src/utils`: 106 files, 1751 passing / 1 skipped.

Test-hygiene follow-up from review: the trailing `mockRestore()` calls are gone — `main` enables `mockReset`/`restoreMocks` globally, so the runner restores spies before every test regardless of whether the previous test's assertions passed. Confirmed the suite is still behaviour-sensitive — reverting either `isPageUnloading()` guard or the 401 `warn` branch fails tests.

Unit tests cover the page-discard path (list and detail), the frozen-page path (asserting the failure still reports), the restored-page path, the `401`, a `5xx`, a real network error, and a malformed body — each asserting which of them report. The lifecycle cases drive the public fetchers and assert only on reporting behaviour, not on how the discard is detected.

## Background

This came out of a goal run against the Cloud frontend error-free-sessions dashboard, measured over a rolling 7-day window ending 2026-07-31. Baseline: error-free sessions 17–22% daily, 8,662 of 10,790 sessions containing at least one error; target ≥90% daily. The three clusters this addresses — `TypeError: Failed to fetch` (554 sessions), `401` (113), `403` (79) — are 746 sessions/week combined, about 18% of the residual error sessions once the extension-loading 404 cluster is excluded. The first two stop reporting; the third is left reporting on purpose, per above. Those numbers are as reported on the dashboard at the time and were not re-queried while making this change.

## Provenance

**Authored by:** agent-work loop

**Verified:** on the tree with current `main` merged in: `pnpm typecheck`, `pnpm lint` (0 errors), `pnpm format` and `pnpm knip` clean; `vitest run` over the jobs/queue/assets/missingMedia/utils consumers — 113 files, 1885 passing / 1 skipped.

**Deviations:** `main` was merged in to resolve a stale-branch CI failure (`upload-e2e-coverage` sparse-checks-out a script this branch predates) and two semantic conflicts — `fetchJobAssets` needing the teardown guard, and the mock-cleanup change being reverted because `main` now forbids it by lint. One review finding was declined rather than fixed (routing these failures through a `reportError()`/`errorType` reporting seam) — no such facility or guideline exists in the repo, and the nearest thing that does, `globalThis.reportError`, is what Datadog RUM captures as an unhandled error; the reasoning is on that thread. The abort-signal mechanism described in earlier revisions of this description was removed in review — see the `pageTeardownUtil.ts` thread. Two review findings were deferred rather than fixed here (typed lifecycle result on a 401; propagating a cancelled request instead of returning an empty page); both are filed as follow-ups and both are pre-existing behaviour, not regressions introduced by this PR.

### CODE REVIEW

**Comment by mattmillerai** [comment]
Verification note: a whole-repo `vitest run` on this branch finished with 14,158 passing and 1 failing test across 24 file-level errors. I could not attribute those without a same-machine baseline run on `main` (out of time budget), and they are not in the areas this change touches — the scoped run over `src/platform/remote/comfyui/jobs`, `src/platform/missingMedia`, `src/stores/queueStore.test.ts`, `src/services/jobOutputCache.test.ts` and `src/utils` is fully green (50 files / 953 tests), as are typecheck, lint, format and knip. CI's run against the merge base is the authoritative signal here.

File: src/platform/remote/comfyui/jobs/fetchJobs.ts [hunk 1]
```diff
@@ -67,8 +77,11 @@ async function fetchJobsRaw(
       hasMore: data.pagination.has_more
     }
   } catch (error) {
+    // `signal.aborted` rather than the error shape: a request cancelled while
+    // the page unloads can surface as a bare `TypeError: Failed to fetch`.
+    if (signal.aborted || isAbortError(error)) return noJobs
```
[the remark this answers is not in the document]
Comment (mattmillerai) [reply src/platform/remote/comfyui/jobs/fetchJobs.ts]: Partly fixed here, remainder deferred.

The scenario cited — mobile `pagehide` on app-switch — was the real regression risk, and it is gone: the listener now ignores a persisted `pagehide` (a back/forward-cache freeze), so a page that keeps running never has its poll cancelled. A new test asserts the signal stays unaborted and the failure still reports on that path. The controller is re-minted on `pageshow` instead of immediately after the abort, which also covers a browser that reports a non-persisted `pagehide` for a page it then restores.

The return-contract half — rethrowing so callers can tell "no jobs" from "cancelled" — is deliberately not in this PR. It cascades into `api.getQueue`/`api.getHistory`, `queueStore`, `assetsStore` and `missingMediaAssetResolver`, and each newly-propagated rejection needs its own abort guard at the log site or it re-introduces exactly the console noise this PR removes. That is a behavioural change to the jobs fetch contract, not a logging cleanup. Filed as a follow-up with the call-site analysis (all four consumers already preserve state on a throw, so the work is well-specified).

File: src/platform/remote/comfyui/jobs/fetchJobs.ts [hunk 2]
```diff
@@ -159,7 +172,7 @@ export async function fetchQueue(
  * Fetches full job details from /jobs/{job_id}
  */
 export async function fetchJobDetail(
-  fetchApi: (url: string) => Promise<Response>,
+  fetchApi: JobsApiFetcher,
```
[the remark this answers is not in the document]
Comment (mattmillerai) [reply src/platform/remote/comfyui/jobs/fetchJobs.ts]: Fixed. `fetchJobDetail` now passes `{ signal: pageTeardownSignal() }` and guards its catch with `signal.aborted || isAbortError(error)`, matching the list fetchers. Test added; the existing call-site assertion in `getWorkflowFromHistory.test.ts` updated for the second argument.

File: src/utils/pageTeardownUtil.ts [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+ * controller is replaced after each abort rather than latching.
+ */
+let controller = new AbortController()
+
+function abortInFlightRequests() {
+  controller.abort()
+  controller = new AbortController()
+}
+
+window.addEventListener('pagehide', abortInFlightRequests)
```
[the remark this answers is not in the document]
Comment (mattmillerai) [reply src/utils/pageTeardownUtil.ts]: Fixed — registration is now behind `if (typeof window !== 'undefined')`.

File: src/utils/pageTeardownUtil.ts [hunk 4]
```diff
@@ -0,0 +1,24 @@
...
+ * `pagehide` rather than `beforeunload`, which also fires for navigations the
+ * user then cancels — nothing should be aborted while the page keeps running.
+ * A hidden page can still come back from the back/forward cache, so the
+ * controller is replaced after each abort rather than latching.
+ */
+let controller = new AbortController()
+
+function abortInFlightRequests() {
+  controller.abort()
+  controller = new AbortController()
```
[the remark this answers is not in the document]
Comment (mattmillerai) [reply src/utils/pageTeardownUtil.ts]: Adopted. The controller is re-minted on `pageshow` now, so the aborted signal stays in effect for the whole teardown window; and it aborts only on a non-persisted `pagehide`, so a back/forward-cache freeze is not treated as a teardown in the first place. Together those also close the "settled empty snapshot on a surviving page" risk raised on `fetchJobs.ts`.

File: src/platform/remote/comfyui/jobs/fetchJobs.ts [hunk 5]
```diff
@@ -39,24 +43,30 @@ export interface FetchHistoryPageResult {
...
+    jobs: [],
+    total: 0,
+    offset,
+    limit: maxItems,
+    hasMore: false
+  }
+  const signal = pageTeardownSignal()
   try {
-    const res = await fetchApi(url)
+    const res = await fetchApi(url, { signal })
```
[the remark this answers is not in the document]
Comment (mattmillerai) [reply src/platform/remote/comfyui/jobs/fetchJobs.ts]: Not taking this one. It is pre-existing and outside a logging-classification change, and the accumulation half of the claim does not hold for the polled path: `queueStore.update()` short-circuits on its own `inFlight` flag, and `useQueuePolling` only schedules while `!queueStore.isLoading`, so a stalled request blocks the next poll rather than stacking up.

A blanket `AbortSignal.timeout` on the jobs poll is also not obviously an improvement — it would turn a slow-but-valid response into an empty result set, which is the failure mode the rest of this review is trying to avoid. If the hang is worth addressing it belongs at the shared request seam with a deliberate budget, not bolted onto this fetcher.

**Comment by mattmillerai** [comment]
🤖 The reviews loop filed Linear follow-up ticket(s) for review thread(s) deferred as out of scope for this PR:
- [BE-5680](https://linear.app/comfyorg/issue/BE-5680) — Propagate cancelled jobs requests instead of returning an empty result set — filed as `agent-spike` (premise unverified)

The following carry `agent-spike` instead of `agent-ok` because their reachability claim was not backed by evidence (BE-5378) — the claim is investigated before any code is written, and "the premise does not hold" is a valid, successful outcome:
- **Propagate cancelled jobs requests instead of returning an empty result set** — no reachability block in the proposal

**Review by christian-byrne — COMMENTED** [review]
Can you reconcile this was other OPEN PRs on the repo with similar approach/intent? In general, reporting of errors should not incite us to remove the reporting but rather address the bug.

File: src/platform/remote/comfyui/jobs/fetchJobs.ts [hunk 6]
```diff
@@ -39,24 +43,30 @@ export interface FetchHistoryPageResult {
...
-      console.error(`[Jobs API] Failed to fetch jobs: ${res.status}`)
-      return {
-        jobs: [],
-        total: 0,
-        offset,
-        limit: maxItems,
-        hasMore: false
-      }
+      const message = `[Jobs API] Failed to fetch jobs: ${res.status}`
+      // A poll that outran the session is a lifecycle state, not a fault: the
```
Comment (DrJKL) [inline src/platform/remote/comfyui/jobs/fetchJobs.ts:68]: A 401 is not enough to prove that a poll belongs to a discarded session. Return a typed authentication/lifecycle result and let the session owner decide whether existing data is retained or cleared instead of converting every 401 to an authoritative empty result.

File: src/utils/pageTeardownUtil.ts [hunk 7]
```diff
@@ -0,0 +1,32 @@
+/**
```
Comment (DrJKL) [inline src/utils/pageTeardownUtil.ts:1]: Do not create one global controller for unrelated requests. Give the request or authenticated session owner an `AbortController`, pass its signal into fetch, and abort it when that owner ends. That removes the page-event singleton and its explanatory block.

File: src/platform/remote/comfyui/jobs/fetchJobs.test.ts [hunk 8]
```diff
@@ -61,7 +74,8 @@ describe('fetchJobs', () => {
       const result = await fetchHistory(mockFetch)
 
       expect(mockFetch).toHaveBeenCalledWith(
-        '/jobs?status=completed,failed,cancelled&limit=200&offset=0'
+        '/jobs?status=completed,failed,cancelled&limit=200&offset=0',
+        { signal: expect.any(AbortSignal) }
```
Comment (DrJKL) [inline src/platform/remote/comfyui/jobs/fetchJobs.test.ts]: This asserts signal plumbing rather than cancellation behavior. Drive cancellation through the owning public operation and assert the stale request cannot report or commit. Remove the repeated `expect.any(AbortSignal)` argument checks once behavior is covered.

**Review by DrJKL — CHANGES_REQUESTED** [review]
The change introduces a global page-lifecycle controller and comments that justify treating request ownership as process-wide.

File: src/utils/pageTeardownUtil.ts (hunk 7 above)
Comment (mattmillerai) [reply src/utils/pageTeardownUtil.ts:1]: Fixed by deleting the controller rather than relocating it — c57aa4c.

You're right that it shouldn't own unrelated requests, and looking again it never needed to own any: the browser already cancels in-flight requests when it discards the page, so `abort()` cancelled nothing that wasn't being cancelled anyway. The only thing the controller contributed was a readable bit — "is this page going away?" — which the catch block used to tell an ordinary page exit from a real network fault. That bit is now just a predicate:

```ts
export function isPageUnloading(): boolean
```

No `AbortController`, no signal threaded through fetch, and the four fetchers go back to their original `(url: string) => Promise<Response>` seam. The explanatory block you objected to went with it; what's left documents only why `pagehide` and not `beforeunload`, and why a persisted `pagehide` doesn't count — neither of which is derivable from the code.

The explicit `AbortError` guard is gone too: nothing in the request seam attaches a signal, so that branch was unreachable.

On the module-level flag that remains — page discard genuinely is document-wide state, so I don't think a per-owner `AbortController` models it; there's no session whose lifetime is "until this document is destroyed" other than the document. The difference from what you flagged is that it no longer claims to own anyone's requests, it just reports a fact about the page.

File: src/platform/remote/comfyui/jobs/fetchJobs.test.ts (hunk 8 above)
Comment (mattmillerai) [reply src/platform/remote/comfyui/jobs/fetchJobs.test.ts]: Fixed — the assertions are gone along with the thing they were asserting.

There is no signal plumbed into fetch any more (see the `pageTeardownUtil.ts` thread), so every `expect.any(AbortSignal)` argument check and the `mock.calls[0][1].signal.aborted` check are deleted; call-shape assertions are back to `toHaveBeenCalledWith(url)`.

The lifecycle cases now drive the public operation and assert only on outcome — `fetchHistory`/`fetchJobDetail` is called with a `pagehide`/`pageshow` dispatched around it, and the assertion is whether the failure reported:

- discard (`pagehide`, not persisted) → no `console.error`
- freeze (`pagehide`, persisted) → still `console.error`
- restore (`pagehide` then `pageshow`) → still `console.error`

The explicit-`AbortError` test is dropped rather than rewritten: that branch was unreachable through any public path, and the guard behind it is gone.

File: src/platform/remote/comfyui/jobs/fetchJobs.ts (hunk 6 above)
Comment (mattmillerai) [reply src/platform/remote/comfyui/jobs/fetchJobs.ts:68]: Agreed on the substance, but deferred rather than done here — the empty result on a 401 is pre-existing, not something this PR introduces.

Before this change `fetchJobsRaw` already returned `{ jobs: [], total: 0, offset, limit, hasMore: false }` for *every* non-ok status, 401 included. The diff extracted that literal into a `noJobs` const and changed the log level from `console.error` to `console.warn`. So the "authoritative empty result" you're describing ships today and is unchanged either way by this PR.

A typed authentication/lifecycle result is the right shape and I want it. It just isn't small from here: `fetchJobsRaw`'s return type feeds `fetchHistory`/`fetchHistoryPage`/`fetchQueue`, which are `api.getQueue`/`api.getHistory` — an extension-facing surface — which are consumed by `queueStore`, `assetsStore` and `missingMediaAssetResolver`. Each has to learn to hold its existing data on a lifecycle result instead of committing an empty one, and `api.getQueue`'s contract change needs a deliberate call. Burying that in a log-level PR is how it gets shipped without anyone weighing it.

Filed as a follow-up with that call-site list (it overlaps BE-5680, which covers the same contract problem for the cancelled-request case — likely one piece of work).

Resolving so it's not lost now that it's tracked; reopen if you'd rather this PR block on it.

**Comment by mattmillerai** [comment]
@christian-byrne — on both points.

**This doesn't remove reporting.** Four of the six failure paths are untouched: after this PR `fetchJobsRaw` still logs `console.error` for a 403, a 5xx, a response body that fails schema validation, and a genuine network fault. Two change. A 401 drops to `console.warn` — still logged, still visible, just not counted as an error session. And a request the browser cancels because the page is being discarded isn't logged, because there is no bug behind it to find: the user closed the tab.

**On addressing the bug instead.** For the 401 I went looking for one first, and the gate the ticket assumed was missing already exists — `fetchApi` awaits `waitForAuthInitialization` before every cloud request, and a 401 response is already retried once behind a token re-mint (`fetchWithUnifiedRemint`). What still reaches this code is a poll that outran its session. There *is* a real design problem underneath it, which @DrJKL raised on this PR: a 401 currently settles an empty job list over the store rather than holding the existing one. That's pre-existing behaviour and I've filed it as its own change rather than smuggle a fetch-contract change into a log-level PR.

The 403 is where I think your instinct is exactly right, so I deliberately left it alone: ~79 sessions/week that are almost certainly a mix of an expected terminal state and a possible real authorisation bug, and we can't currently tell them apart because we log the status code and throw away the response body's machine-readable error type. Kept at `console.error` on purpose, with a follow-up to surface that error type so the cluster can be split and the real defect, if there is one, found.

**Other open PRs.** The closest in intent is #16173 (group Firebase Auth errors under a stable RUM fingerprint) — same goal, and also non-destructive: it re-groups rather than silences, preserving message and stack. I didn't find another open PR touching the jobs fetchers or this error path. If you had specific ones in mind, point me at them and I'll reconcile against those.

**Comment by mattmillerai** [comment]
🤖 The reviews loop filed Linear follow-up ticket(s) for review thread(s) deferred as out of scope for this PR:
- [BE-11602](https://linear.app/comfyorg/issue/BE-11602) — Hold existing jobs data on an auth failure instead of committing an empty job list — filed as `agent-spike` (premise unverified)

The following carry `agent-spike` instead of `agent-ok` because their reachability claim was not backed by evidence (BE-5378) — the claim is investigated before any code is written, and "the premise does not hold" is a valid, successful outcome:
- **Hold existing jobs data on an auth failure instead of committing an empty job list** — no reachability block in the proposal

File: src/platform/remote/comfyui/jobs/fetchJobs.test.ts [hunk 9]
```diff
@@ -45,6 +54,10 @@ function createMockResponse(
 }
 
 describe('fetchJobs', () => {
+  beforeEach(() => {
+    dispatchPageTransition('pageshow', { persisted: true })
+  })
```
[the remark this answers is not in the document]
Comment (mattmillerai) [reply src/platform/remote/comfyui/jobs/fetchJobs.test.ts:60]: Fixed in 96b9be7 — `vi.resetAllMocks()` now runs in the `beforeEach` alongside the lifecycle reset, and the twelve trailing `mockRestore()` calls are gone rather than kept as a redundant second mechanism. The trailing restore was exactly the fragile part: it sits after the assertions, so a failing test skipped it and leaked its `console` spy into the rest of the file.

Verified the suite is still behaviour-sensitive after the change: reverting the `isPageUnloading()` guard and the 401 `warn` branch in `fetchJobs.ts` fails 2 of the 24 tests.

File: src/platform/remote/comfyui/jobs/fetchJobs.ts [hunk 10]
```diff
@@ -46,17 +47,22 @@ async function fetchJobsRaw(
...
+      // request seam already waits for auth to resolve and re-mints once on 401.
+      if (res.status === 401) console.warn(message)
+      else console.error(message)
```
[the remark this answers is not in the document]
Comment (mattmillerai) [reply src/platform/remote/comfyui/jobs/fetchJobs.ts:71]: Not taking this one — it would undo the change. Three things, checked rather than assumed:

**There is no such coding guideline.** `grep -rin "reportError\|report failures" docs/guidance/*.md docs/testing/*.md` returns nothing, and the `.coderabbit.yaml` path instruction for `**/*.ts` points only at `docs/guidance/typescript.md`, which has no reporting rule. The "stable `errorType`" convention does not exist either: `errorType` appears in `src/` only as domain-local fields — a telemetry argument in `src/platform/cloud/onboarding/auth.ts:19` and a validation-catalog key in `src/platform/errorCatalog/` — not as a reporting taxonomy anything could join.

**There is no `reportError()` to call.** The only definition in `src/` is a local closure at `src/composables/auth/useAuthActions.ts:42`. It is Firebase-auth-specific (it branches on `FirebaseError` codes) and its effect is a user-facing error toast. Wiring a background jobs poll into it would pop a toast at the user every time a poll fails — a regression, not a fix.

**The other reading is the one this PR is undoing.** If `globalThis.reportError` is meant, `src/composables/useImageQuiet.ts:8` documents what that does here: "our error monitoring (Datadog RUM) captures [it] as an unhandled error". That file exists precisely to stop routing expected failures there. These jobs-poll paths are handled — every one returns the same empty result set and the UI carries on — so sending them to `globalThis.reportError` would re-create the error sessions this PR removes, and would be strictly louder than the `console.error` they use today.

Worth noting the lines are also pre-existing: `fetchJobs.ts:79` and `:185` logged via `console.error` before this PR. The diff only added the lifecycle guard in front of them and split 401 down to `warn`; the 5xx, malformed-body and genuine-network-fault paths you list are deliberately still `console.error`, unchanged.

Not filing a follow-up: there is no reporting facility to migrate to and no guideline asking for one, so there is nothing well-specified to hand off. If we do want a structured reporting seam for handled backend failures, that is its own design call about what belongs in RUM — the opposite direction from this PR, and not something to settle in a thread here.

File: src/platform/remote/comfyui/jobs/fetchJobs.test.ts (hunk 9 above)
[the remark this answers is not in the document]
Comment (mattmillerai) [reply src/platform/remote/comfyui/jobs/fetchJobs.test.ts:60]: Correction to my reply above — I have merged current `main` into this branch, and on the merged tree the requested fix is a lint error, so it is now reverted.

`main` sets `mockReset: true` and `restoreMocks: true` globally (`vite.config.mts:819-820`), so the runner already resets mocks and restores spies **before every test**. That is strictly stronger than what was asked for: it does not depend on a hook running, and it does not depend on the previous test's assertions passing — which was the actual concern. `main` also added a custom rule, `comfy/no-redundant-vitest-cleanup` (error, `.oxlintrc.json:147`), that flags `vi.resetAllMocks()` in a Vitest hook precisely because the setup does it. With the line in, `pnpm lint` failed:

```
src/platform/remote/comfyui/jobs/fetchJobs.test.ts:59:5: error comfy(no-redundant-vitest-cleanup):
vi.resetAllMocks() is redundant in a Vitest hook because the project test setup performs this cleanup automatically.
```

The path instruction cited (`docs/testing/vitest-patterns.md`) now says the opposite of the quoted line — its "Automatic mock cleanup" section reads "Do not call the corresponding cleanup APIs in `beforeEach` or `afterEach`." The review was run against this PR's base (`31434472`, ~1 month stale), which predates that rewrite.

What I kept from the finding: the twelve trailing `mockRestore()` calls are gone. They were the fragile part and they are redundant under `restoreMocks: true`. The `beforeEach` retains only the `pageshow` dispatch, which resets module-level lifecycle state, not a mock.

36 tests pass on the merged tree; `pnpm lint` is back to 0 errors.

**Comment by mattmillerai** [comment]
Merged current `main` into this branch (`b26af71`) — the branch was ~1 month stale, and that was causing a real CI failure plus two semantic conflicts that only appear in the merged result.

**CI failure (`upload-e2e-coverage / package`, exit 127).** `main`'s `ci-tests-e2e.yaml` now has an `upload-e2e-coverage` job calling the reusable `ci-tests-e2e-coverage-package.yaml`, which sparse-checks-out `scripts/cicd/package-e2e-coverage.sh` at `github.event.pull_request.head.sha` — i.e. at *this branch*, which predates that script. So the step ran `scripts/cicd/package-e2e-coverage.sh: No such file or directory`. Nothing to fix in the diff; the merge resolves it.

**Semantic conflict 1 — `fetchJobAssets`.** `main` added a fourth jobs fetcher (#13681) after this branch was written. Its catch does an unconditional `console.error`, so a request the browser cancels at page discard reports exactly the noise this PR removes — the merge is textually clean but reopens the hole. Added the same `isPageUnloading()` guard the other three fetchers use, plus a test. Confirmed the test is load-bearing: without the guard it fails.

**Semantic conflict 2 — mock cleanup.** Detailed on the CodeRabbit thread. `main` now enables `mockReset`/`restoreMocks` globally and added a lint rule forbidding `vi.resetAllMocks()` in a hook, so the change I pushed in `96b9be7` for that finding is reverted; the redundant trailing `mockRestore()` calls stay removed.

Verified on the merged tree: `pnpm typecheck`, `pnpm lint` (0 errors), `pnpm format`, `pnpm knip` clean; `vitest run` over the jobs/queue/assets/missingMedia/utils consumers — 113 files, 1885 passing / 1 skipped.

All review threads are resolved. Re-requested review from @DrJKL, whose inline findings were addressed in `c57aa4c`.
