### ISSUE TITLE
[Bug]: Cannot load any workflow since 1.9.9

### ISSUE THREAD

**Issue by melMass** [Comfy-Org/ComfyUI_frontend#2488]
### Frontend Version

Since updating to 1.9.9 I can't load any worfklow. I'm going to try to downgrade but I believe it comes from the update but the stacktrace being catch by the error widget makes it a bit hard to track

![Image](https://github.com/user-attachments/assets/8f686ed1-ecff-4485-a4a5-fc0409fc580d)

### Expected Behavior

Load workflow

### Actual Behavior

`TypeError: (intermediate value).entries is not a function` with various stack trace

### Steps to Reproduce

1. Update to 1.9.9
2. Load a workflow

### Debug Logs

```powershell
-
```

### Browser Logs

500+ `Parameter defaultValue is deprecated. The default value in settings definition will be used instead.`

but nothing else relevant

### Setting JSON

```json
{
    "Comfy.NodeSuggestions.number": 25,
    "Comfy.ColorPalette": "rosepine",
    "mtb.imageFeed.enabled": false,
    "Comfy.LinkRenderMode": 2,
    "mtb.Debug.enabled": true,
    "Comfy.DevMode": true,
    "Comfy.UseNewMenu": "Top",
    "VHS.AdvancedPreviews": true,
    "ADE.ShowExperimental": true,
    "AE.details": true,
    "Comfy.NodeSearchBoxImpl": "default",
    "Comfy.Sidebar.Size": "small",
    "Comfy.TextareaWidget.FontSize": 13,
    "Comfy.DisableSliders": true,
    "Comfy.EnableTooltips": true,
    "Comfy.NodeInputConversionSubmenus": false,
    "Comfy.Sidebar.Location": "left",
    "Comfy.SnapToGrid.GridSize": 12,
    "Comfy.NodeLibrary.Bookmarks": [],
    "Comfy.Node.ShowDeprecated": true,
    "Comfy.LinkRelease.Action": "search box",
    "Comfy.LinkRelease.ActionShift": "context menu",
    "Comfy.Queue.ImageFit": "cover",
    "mtb.notePlus.useShiki": true,
    "mtb.Use Shiki": false,
    "mtb.io-sidebar.count": 10000,
    "mtb.Main.debug-enabled": true,
    "mtb.Main.image-feed-enabled": false,
    "pysssss.SnapToGrid": true,
    "Comfy.Settings.ExtensionPanel": true,
    "Comfy.Validation.NodeDefs": true,
    "Comfy.Workflow.WorkflowTabsPosition": "Topbar",
    "Comfy.Workflow.ShowMissingModelsWarning": true,
    "Comfy.CustomColorPalettes": {
        "rosepine": {
            "id": "rosepine",
            "name": "Rose Pine",
            "colors": {
                "node_slot": {
                    "*": "",
                    "ACCUMULATION": "",
                    "ACNAUTOSIZE": "",
                    "ADEAUTOSIZE": "",
                    "ADEWARN": "",
                    "AD_BLOCK": "",
                    "AD_KEYFRAMES": "",
                    "AD_SETTINGS": "",
                    "ATTN_BANK": "",
                    "ATTN_INJ": "",
                    "ATTN_OVERRIDE": "",
                    "AUDIO": "",
                    "AUDIOUPLOAD": "",
                    "AUDIO_UI": "",
                    "BASIC_PIPE": "",
                    "BATCH_COORDINATES": "",
                    "BBOX": "",
                    "BBOX_DETECTOR": "",
                    "BOOLEAN": "",
                    "CAMERACTRL_POSES": "",
                    "CFG_EXTRAS": "",
                    "CLIP": "#eacb8b",
                    "CLIPSEGMODEL": "",
                    "CLIP_SEG": "",
                    "CLIP_VISION": "#A8DADC",
                    "CLIP_VISION_OUTPUT": "#ad7452",
                    "CN_WEIGHTS_EXTRAS": "",
                    "COGCONTEXT": "",
                    "COGLORA": "",
                    "COGVIDECONTROLNET": "",
                    "COGVIDECONTROLNETMODEL": "",
                    "COGVIDEOMODEL": "",
                    "COLOR": "",
                    "COMPILEARGS": "",
                    "CONDITIONING": "#cf876f",
                    "CONTEXTREF_KEYFRAME": "",
                    "CONTEXTREF_MODE": "",
                    "CONTEXTREF_TUNE": "",
                    "CONTEXT_EXTRAS": "",
                    "CONTEXT_OPTIONS": "",
                    "CONTROL_NET": "#00d78d",
                    "CONTROL_NET_STACK": "",
                    "CONTROL_NET_WEIGHTS": "",
                    "COSYVOICE_MODEL": "",
                    "CROP_SIZE": "",
                    "CUSTOM_CFG": "",
                    "ControlNetCondition": "",
                    "DAMODEL": "",
                    "DCMODEL": "",
                    "DCNOISE": "",
                    "DC_CN_MODEL": "",
                    "DC_CONTROL": "",
                    "DEPENDENCIES": "",
                    "DETAILER_HOOK": "",
                    "DETAILER_PIPE": "",
                    "DOUBLE_LAYERS": "",
                    "EMBEDS": "",
                    "FACEENHANCE_MODEL": "",
                    "FACESWAP_MODEL": "",
                    "FACE_ANALYSIS_MODEL": "",
                    "FASTERCACHEARGS": "",
                    "FEATURES_3D": "",
                    "FILM_MODEL": "",
                    "FIZZFRAME": "",
                    "FLOAT": "",
                    "FLOATS": "",
                    "FLOAT_CURVE": "",
                    "FLOW": "",
                    "FLOW_CONFIG": "",
                    "FLOW_CONTROL": "",
                    "FluxControlNet": "",
                    "GIF": "",
                    "GLIGEN": "",
                    "GLSL_BUFFERS": "",
                    "GLSL_CODE": "",
                    "GLSL_CONTEXT": "",
                    "GLSL_STRING": "",
                    "GUIDER": "",
                    "HOOKS": "",
                    "HOOK_KEYFRAMES": "",
                    "IMAGE": "#80a1c0",
                    "IMAGEUPLOAD": "",
                    "IMAGE_INJECT": "",
                    "IMAGE_INJECT_OPTIONS": "",
                    "INDEXES": "",
                    "INJ_CONFIG": "",
                    "INSIGHTFACE": "",
                    "INT": "",
                    "INT:seed": "",
                    "INTERPOLATION_STATES": "",
                    "INTS": "",
                    "IPADAPTER": "",
                    "IPADAPTER_PARAMS": "",
                    "IPADAPTER_PIPE": "",
                    "IP_ADAPTER_FLUX": "",
                    "ITERATION_OPTS": "",
                    "JSON": "",
                    "KSAMPLER": "",
                    "KSAMPLER_ADVANCED": "",
                    "LATENT": "#b38ead",
                    "LATENT_KEYFRAME": "",
                    "LATENT_OPERATION": "",
                    "LIST": "",
                    "LIVEPORTRAITPIPE": "",
                    "LORA_PARAMS": "",
                    "LORA_STACK": "",
                    "LP_KEYPOINTS": "",
                    "LP_LANDMARKS": "",
                    "LP_TRACKDATA": "",
                    "LTX_BLOCKS": "",
                    "MASK": "#a3bd8d",
                    "MESH": "",
                    "MODEL": "#8978a7",
                    "MOTION_LORA": "",
                    "MOTION_MODEL_ADE": "",
                    "MULTIVAL": "",
                    "M_C2O": "",
                    "M_MODELS": "",
                    "NAIVEREUSE_KEYFRAME": "",
                    "NOISE": "",
                    "NOISE_LAYERS": "",
                    "NORMALIZED_AMPLITUDE": "",
                    "NUMBER": "",
                    "OPTICAL_FLOW": "",
                    "PER_BLOCK": "",
                    "PE_ADJUST": "",
                    "PHOTOMAKER": "",
                    "PIA_INPUT": "",
                    "PIVOT_CONFIG": "",
                    "PK_HOOK": "",
                    "PLAYLIST": "",
                    "PLUS_INPUT": "",
                    "POSE_KEYPOINT": "",
                    "RAVE_CONFIG": "",
                    "REGIONAL_PROMPTS": "",
                    "REGION_COND": "",
                    "REMBG_SESSION": "",
                    "RGTHREE_CONTEXT": "",
                    "SAM2INFERENCESTATE": "",
                    "SAM2MODEL": "",
                    "SAMPLER": "",
                    "SAMPLER_PARAMS": "",
                    "SAMPLE_SETTINGS": "",
                    "SAM_MODEL": "",
                    "SCA_CONFIG": "",
                    "SCHEDULER_FUNC": "",
                    "SCRIPT": "",
                    "SDXL_TUPLE": "",
                    "SEGM_DETECTOR": "",
                    "SEGS": "",
                    "SEGS_HEADER": "",
                    "SEGS_PREPROCESSOR": "",
                    "SEG_ELT": "",
                    "SEG_ELT_bbox": "",
                    "SEG_ELT_control_net_wrapper": "",
                    "SEG_ELT_crop_region": "",
                    "SELECTEDBLOCKS": "",
                    "SIGMAS": "",
                    "SIGMA_SCHEDULE": "",
                    "SINGLE_LAYERS": "",
                    "SPARSE_METHOD": "",
                    "SRT": "",
                    "SRTPLOAD": "",
                    "STRING": "",
                    "STYLE_MODEL": "#C2FFAE",
                    "T2I_ADAPTER_WEIGHTS": "",
                    "TAESD": "#DCC274",
                    "TEMPORAL_CONFIG": "",
                    "TIMESTEPS_RANGE": "",
                    "TIMESTEP_KEYFRAME": "",
                    "TORAFEATURES": "",
                    "TORAMODEL": "",
                    "TRACKING": "",
                    "TRANSFORMERBLOCKS": "",
                    "TRANSFORMERS_CLASSIFIER": "",
                    "TRIPOSR_MODEL": "",
                    "TUPLE": "",
                    "UNIFORMS": "",
                    "UPSCALER": "",
                    "UPSCALER_HOOK": "",
                    "UPSCALE_MODEL": "",
                    "VAE": "#be616b",
                    "VALUES_REPLACE": "",
                    "VEC2": "",
                    "VEC2POS": "",
                    "VEC3": "",
                    "VEC3POS": "",
                    "VEC4": "",
                    "VEC4COLOR": "",
                    "VHS_AUDIO": "",
                    "VHS_BatchManager": "",
                    "VHS_DUMMY_NONE": "",
                    "VHS_FILENAMES": "",
                    "VHS_VIDEOINFO": "",
                    "VIDEO": "",
                    "VIEW_OPTS": "",
                    "VITMATTE_MODEL": "",
                    "WEBCAM": "",
                    "WEIGHTS_STRATEGY": "",
                    "WEIGHT_ADJUST": "",
                    "XY": ""
                },
                "litegraph_base": {
                    "BACKGROUND_IMAGE": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkAQMAAABKLAcXAAAAAXNSR0IB2cksfwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAZQTFRFKyY3HhwnvrQwygAAADhJREFUeJxjZEAGjKg8+wMIzkfa8BZIsDE1JIAJQUb7gBBRNkcIkYguN+qWUbeMumXULUPXLcg8ABK12UXUEattAAAAAElFTkSuQmCC",
                    "CLEAR_BACKGROUND_COLOR": "#191724",
                    "NODE_TITLE_COLOR": "#908caa",
                    "NODE_SELECTED_TITLE_COLOR": "#e0def4",
                    "NODE_TEXT_SIZE": 14,
                    "NODE_TEXT_COLOR": "#e0def4",
                    "NODE_SUBTEXT_SIZE": 12,
                    "NODE_DEFAULT_COLOR": "#26233a",
                    "NODE_DEFAULT_BGCOLOR": "#1f1d2e",
                    "NODE_DEFAULT_BOXCOLOR": "#6e6a86",
                    "NODE_DEFAULT_SHAPE": "box",
                    "NODE_BOX_OUTLINE_COLOR": "#ebbcba",
                    "NODE_BYPASS_BGCOLOR": "#eb6f92",
                    "DEFAULT_SHADOW_COLOR": "rgba(0,0,0,0.5)",
                    "DEFAULT_GROUP_FONT": 24,
                    "WIDGET_BGCOLOR": "#26233a",
                    "WIDGET_OUTLINE_COLOR": "#6e6a86",
                    "WIDGET_TEXT_COLOR": "#e0def4",
                    "WIDGET_SECONDARY_TEXT_COLOR": "#908caa",
                    "LINK_COLOR": "#9ccfd8",
                    "EVENT_LINK_COLOR": "#f6c177",
                    "CONNECTING_LINK_COLOR": "#31748f"
                },
                "comfy_base": {
                    "fg-color": "#e0def4",
                    "bg-color": "#191724",
                    "comfy-menu-bg": "#1f1d2e",
                    "comfy-input-bg": "#26233a",
                    "input-text": "#e0def4",
                    "descrip-text": "#908caa",
                    "drag-text": "#c4a7e7",
                    "error-text": "#eb6f92",
                    "border-color": "#6e6a86",
                    "tr-even-bg-color": "#26233a",
                    "tr-odd-bg-color": "#1f1d2e",
                    "content-bg": "#403d52",
                    "content-fg": "#e0def4",
                    "content-hover-bg": "#26233a",
                    "content-hover-fg": "#ebbcba"
                }
            }
        }
    },
    "Comfy.TutorialCompleted": true
}
```

### What browsers do you use to access the UI ?

Mozilla Firefox

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-2488-Bug-Cannot-load-any-workflow-since-1-9-9-1966d73d3650814ca87dc6731c9da987) by [Unito](https://www.unito.io)

**Comment by melMass** [comment]
Yep confirmed! It works fine using 1.9.8.
In case someone has the same issue in the meantime you can pass this to comfy:

 `--front-end-version Comfy-Org/ComfyUI_frontend@1.9.8`

**Comment by huchenlei** [comment]
Suspected culprit: https://github.com/Comfy-Org/litegraph.js/pull/506

**Comment by huchenlei** [comment]
Seems like widgets are not always `Array` type lol
