### PR TITLE
feat: non-blocking post-signup email-verification nudge with resend

### PR DESCRIPTION
**Pull request by mattmillerai**
## ELI-5

When you sign up with an email and password, nobody ever checks that the email is really yours. This adds a small, friendly banner in the top bar that says "verify your email" and gives you a button to resend the verification link. It never blocks you from using the app — you can dismiss it, and it only shows up for cloud users once we turn the feature on.

## Summary

Adds a non-blocking, cloud-only, feature-flagged (default off) email-verification nudge for authenticated password-provider users whose email is unverified, plus a resend action. Entirely client-side Firebase; no backend changes.

## Changes

- **What**:
  - `useEmailVerification` composable (`src/composables/auth/`):
    - `needsEmailVerification` — authenticated, `emailVerified === false`, and sign-in provider is `password` (Google/GitHub SSO users carry `emailVerified=true` and never see it).
    - `resend()` — `sendEmailVerification(user, { url: origin })`, success toast, maps `auth/too-many-requests` to a friendly cooldown message, and a 60s client-side cooldown to avoid hammering.
    - `refresh()` — `user.reload()` then, if verification flipped, `getIdToken(true)` so subsequent API calls carry the `email_verified=true` claim (lets the backend lazily persist it). Runs on window refocus (only while the nudge is active) and after resend; hides the nudge once verified.
  - `EmailVerificationNudge` topbar banner — dismissible (dismissal persisted to `localStorage`, re-prompted at most once per session), gated on `isCloud` + the feature flag, mounted alongside the existing subscribe chip in `GraphCanvas` and `LinearView`. Never gates a route, dialog, or feature.
  - Credit-specific variant: when the cloud subscription status reports `free_tier_grant_state === 'verification_required'`, the same banner is shown in non-dismissed form with credit copy ("Verify your email to receive free credits").
  - `email_verification_nudge_enabled` feature flag (default **off**) via the existing `useFeatureFlags` mechanism, so rollout/funnel impact is measurable before broad enable.
  - i18n copy under `auth.emailVerification.*`.
- **Breaking**: none.

## Review Focus

- The nudge is strictly presentational — it wraps no route/dialog/feature. Hard-verification was tried before and hurt the signup funnel, hence the default-off flag and dismissibility.
- Reactivity note: Firebase's `User.reload()` mutates `emailVerified` in place without changing the object reference, so the composable bumps an internal tick to re-evaluate the derived state.
- Dismissal semantics: persisted timestamp compared against a per-session start marker, giving "stays dismissed this session, re-prompt once next session."

## Tests

- Composable (vitest): provider filtering (password vs `google.com`), flag/cloud gating, dismissal + cross-session re-prompt, credits variant ignoring dismissal, resend success / `too-many-requests` / generic error, no spurious error toast when a post-send refresh fails, cooldown re-enable, and refresh flip hiding the nudge.
- Component (vitest): renders nothing without an active nudge, generic variant resend/dismiss wiring, credit copy without a dismiss control, resend disabled on cooldown.

## Judgment calls

- Mounted in both the canvas and linear top bars (matching the existing subscribe chip placement); not added to any modal/settings surface.
- The credits variant is also flag-gated so the whole nudge stays behind one rollout switch.

### CODE REVIEW

File: src/composables/auth/useEmailVerification.ts [hunk 1]
```diff
@@ -0,0 +1,166 @@
...
+ * Timestamp captured once when the module loads (app start). A dismissal that
+ * happened before this point belongs to an earlier session, so the nudge is
+ * re-prompted at most once per session while the dismissal itself persists.
+ */
+const SESSION_START_MS = Date.now()
+
+type EmailVerificationNudgeVariant = 'credits' | 'generic'
+
+function readDismissedAt(): number {
+  const raw = localStorage.getItem(DISMISSED_AT_KEY)
```
[the remark this answers is not in the document]
Comment (mattmillerai) [reply src/composables/auth/useEmailVerification.ts]: Fixed in a29f05092 — both `readDismissedAt()` and `dismiss()` now wrap their `localStorage` access in try/catch, so blocked storage no longer crashes topbar rendering or the dismiss handler (falls back to treating the nudge as undismissed / in-memory dismissal). Added a regression test that mounts with `getItem`/`setItem` throwing `SecurityError`.

File: src/composables/auth/useEmailVerification.ts [hunk 2]
```diff
@@ -0,0 +1,166 @@
...
+    } catch (error) {
+      console.error('Failed to refresh email verification status:', error)
+    }
+  }
+
+  async function resend(): Promise<void> {
+    const user = currentUser.value
+    if (!user || !canResend.value) return
+
+    canResend.value = false
```
[the remark this answers is not in the document]
Comment (mattmillerai) [reply src/composables/auth/useEmailVerification.ts:128]: Fixed in a29f05092 — on a non-rate-limit failure the pending cooldown timer is cleared and `canResend` is re-enabled immediately, so a transient network error no longer locks the button for 60s. Rate-limit errors still keep the cooldown. Added regression tests for both branches.

File: src/composables/auth/useEmailVerification.ts [hunk 3]
```diff
@@ -0,0 +1,166 @@
...
+      severity: 'success',
+      summary: t('auth.emailVerification.resentSuccess'),
+      detail: t('auth.emailVerification.resentSuccessDetail'),
+      life: 5000
+    })
+    await refresh()
+  }
+
+  useEventListener(window, 'focus', () => {
+    if (nudgeVariant.value) void refresh()
```
[the remark this answers is not in the document]
Comment (mattmillerai) [reply src/composables/auth/useEmailVerification.ts]: Fixed in a29f05092 — the focus handler now gates on `needsEmailVerification.value` instead of `nudgeVariant.value`, so a dismissed generic nudge still picks up a verification completed in another tab.

File: src/composables/auth/useEmailVerification.ts [hunk 4]
```diff
@@ -0,0 +1,166 @@
...
+    toastStore.add({
+      severity: 'success',
+      summary: t('auth.emailVerification.resentSuccess'),
+      detail: t('auth.emailVerification.resentSuccessDetail'),
+      life: 5000
+    })
+    await refresh()
+  }
+
+  useEventListener(window, 'focus', () => {
```
[the remark this answers is not in the document]
Comment (mattmillerai) [reply src/composables/auth/useEmailVerification.ts:165]: Fixed in a29f05092 — `refresh()` now short-circuits while a refresh is in flight (`isRefreshing` guard), so rapid focus/blur churn no longer issues overlapping `reload()`/`getIdToken(true)` requests.

File: src/composables/auth/useEmailVerification.ts [hunk 5]
```diff
@@ -0,0 +1,166 @@
...
+    if (!user || user.emailVerified) return
+
+    try {
+      await user.reload()
+      reloadTick.value++
+
+      if (user.emailVerified) {
+        // Force a token refresh so subsequent API calls carry the
+        // `email_verified=true` claim, letting the backend lazily persist it.
+        await user.getIdToken(true)
```
[the remark this answers is not in the document]
Comment (mattmillerai) [reply src/composables/auth/useEmailVerification.ts:113]: Not changing this — the degradation is acceptable for a non-blocking nudge. If `reload()` flips `emailVerified` to true but `getIdToken(true)` fails, the nudge correctly disappears (the user *is* verified) and the backend still picks up the `email_verified` claim on the next natural Firebase token refresh (within ~1h). Re-showing the nudge to an already-verified user to force a retry would be a worse UX than a short claim-propagation delay.

File: src/composables/auth/useEmailVerification.ts [hunk 6]
```diff
@@ -0,0 +1,166 @@
...
+    needsEmailVerification,
+    nudgeVariant,
+    canResend,
+    resend,
+    refresh,
+    dismiss
+  }
+}
+
+export const useEmailVerification = createSharedComposable(
```
[the remark this answers is not in the document]
Comment (mattmillerai) [reply src/composables/auth/useEmailVerification.ts:181]: Acknowledged, but intentionally out of scope here. This is a `createSharedComposable`, so `dismissedAt`/`canResend` do survive a same-session logout→login. For a purely cosmetic, non-blocking nudge the worst case is a second user briefly not seeing the nudge (stale dismissal) or a lingering 60s resend cooldown — negligible, and only in the multi-account-same-tab case. Per-user keying would need a design decision on the key/reset strategy that is not warranted for this severity, so leaving as-is.

File: src/composables/auth/useEmailVerification.ts [hunk 7]
```diff
@@ -0,0 +1,166 @@
...
+    const user = currentUser.value
+    if (!user || !canResend.value) return
+
+    canResend.value = false
+    window.setTimeout(() => {
+      canResend.value = true
+    }, RESEND_COOLDOWN_MS)
+
+    try {
+      await sendEmailVerification(user, { url: window.location.origin })
```
[the remark this answers is not in the document]
Comment (mattmillerai) [reply src/composables/auth/useEmailVerification.ts:134]: Not reachable under current deployment — this nudge is cloud-only (`isCloud` gate) and the Comfy cloud app is served from the origin root, so `window.location.origin` is the correct continue URL and no subpath is dropped. Will revisit if/when the app is ever hosted under a subpath.

File: src/components/topbar/EmailVerificationNudge.test.ts [hunk 8]
```diff
@@ -0,0 +1,91 @@
...
+  })
+
+  it('disables resend while on cooldown', () => {
+    h.composable!.nudgeVariant.value = 'generic'
+    h.composable!.canResend.value = false
+    renderNudge()
+
+    expect(
+      screen.getByTestId('email-verification-resend').hasAttribute('disabled')
+    ).toBe(true)
```
[the remark this answers is not in the document]
Comment (mattmillerai) [reply src/components/topbar/EmailVerificationNudge.test.ts]: Done in 2246bb7a49 — the nudge is now selected with `getByRole('status')`, resend/dismiss by accessible name, and the cooldown asserted with `toBeDisabled()`. The `data-testid` attributes stay on the component (they follow the topbar convention and are the hook for future e2e), but no unit test depends on them anymore.

File: src/composables/auth/useEmailVerification.test.ts [hunk 9]
```diff
@@ -0,0 +1,298 @@
...
+}))
+vi.mock('@/platform/distribution/types', () => ({
+  get isCloud() {
+    return mocks.isCloud.current
+  }
+}))
+vi.mock('@/platform/updates/common/toastStore', () => ({
+  useToastStore: () => mocks.toast
+}))
+vi.mock('@/i18n', () => ({ t: (key: string) => key }))
```
[the remark this answers is not in the document]
Comment (mattmillerai) [reply src/composables/auth/useEmailVerification.test.ts]: Done in 2246bb7a49 — the `@/i18n` mock is gone. The composable uses the module-level `t` facade (not `useI18n()`), so no plugin install is needed: the real instance resolves against the shipped English messages. The two toast assertions now check the rendered copy, so a missing or mistyped key fails the test instead of silently echoing back.

File: src/composables/auth/useEmailVerification.test.ts [hunk 10]
```diff
@@ -0,0 +1,298 @@
...
+    getIdToken: vi.fn(),
+    ...overrides
+  }
+}
+
+async function loadComposable() {
+  vi.resetModules()
+  const mod = await import('./useEmailVerification')
+  return mod.useEmailVerification()
+}
```
[the remark this answers is not in the document]
Comment (mattmillerai) [reply src/composables/auth/useEmailVerification.test.ts:60]: Good catch — fixed in 2246bb7a49. `loadComposable()` now runs the composable inside an `effectScope()` that `afterEach()` stops, so `createSharedComposable` tears down and the window `focus` listener unsubscribes before the next `vi.resetModules()`.

File: src/composables/auth/useEmailVerification.test.ts [hunk 11]
```diff
@@ -0,0 +1,298 @@
...
+      mocks.authStore.currentUser = makeUser()
+      mocks.sendEmailVerification.mockResolvedValue(undefined)
+      const { resend, canResend } = await loadComposable()
+
+      await resend()
+      expect(canResend.value).toBe(false)
+
+      await vi.advanceTimersByTimeAsync(60_000)
+      expect(canResend.value).toBe(true)
+    })
```
[the remark this answers is not in the document]
Comment (mattmillerai) [reply src/composables/auth/useEmailVerification.test.ts:270]: Done in 2246bb7a49 — the `resend` suite has a `beforeEach(() => vi.useFakeTimers())`, the local `vi.useFakeTimers()` in the cooldown test is gone, and the file-level `afterEach` now calls `vi.clearAllTimers()` before `vi.useRealTimers()`.

File: src/composables/auth/useEmailVerification.test.ts [hunk 12]
```diff
@@ -0,0 +1,298 @@
...
+      const { needsEmailVerification, refresh } = await loadComposable()
+      expect(needsEmailVerification.value).toBe(true)
+
+      await refresh()
+
+      expect(user.reload).toHaveBeenCalled()
+      expect(user.getIdToken).toHaveBeenCalledWith(true)
+      expect(needsEmailVerification.value).toBe(false)
+    })
+  })
```
[the remark this answers is not in the document]
Comment (mattmillerai) [reply src/composables/auth/useEmailVerification.test.ts:353]: Added both in 2246bb7a49:

- `picks up a verification done in another tab on window focus, even after dismissal` — dismisses, dispatches `focus`, and asserts the refresh ran (verification flips and the token is force-refreshed). Verified it fails when the listener body is removed.
- `collapses overlapping refreshes into a single reload` — two overlapping `refresh()` calls against a pending `reload()` promise assert one `reload()`. Verified it fails when the `isRefreshing` guard is dropped.

File: src/composables/useFeatureFlags.ts [hunk 13]
```diff
@@ -237,6 +238,13 @@ export function useFeatureFlags() {
         'off'
       )
     },
+    get emailVerificationNudgeEnabled() {
+      return resolveFlag(
+        ServerFeatureFlag.EMAIL_VERIFICATION_NUDGE_ENABLED,
+        remoteConfig.value.email_verification_nudge_enabled,
+        false
+      )
+    },
```
[the remark this answers is not in the document]
Comment (mattmillerai) [reply src/composables/useFeatureFlags.ts:265]: Added coverage in 2246bb7a49, mirroring the `onboardingTourEnabled` block: the `false` default (with the rationale that an on-by-default nudge would show to every unverified user when config is unreachable) and the remote-config turn-on, which pins the `email_verification_nudge_enabled` wire key.

Skipped the third case (server-feature-flag fallback): that branch belongs to `resolveFlag`, which already has dedicated coverage in this file for the override/remote-config/server precedence chain — a per-flag copy would just re-test the shared helper.

**Comment by mattmillerai** [comment]
Heads-up on one file in this diff that is not part of the feature: `browser_tests/fixtures/data/workspaceAuthFixtures.ts`.

`lint-and-format` was failing on `pnpm typecheck:browser`:

```
browser_tests/fixtures/data/workspaceAuthFixtures.ts(6,3): error TS2353: Object literal may only specify known properties, and 'team_workspaces_enabled' does not exist in type 'RemoteConfig'.
```

That is a semantic conflict already on `main`, not something this branch introduced: #14613 removed `team_workspaces_enabled` from `RemoteConfig` on Aug 5, and #12940 (written earlier) landed the fixture that sets it as `main`'s current HEAD. `lint-and-format` does not run on pushes to `main`, so it went unnoticed there — but it fails on every PR that merges `main`.

Fix here is the minimal one: drop the retired key so the fixture is an empty `RemoteConfig`. Team-workspace behavior is unconditional after #14613, so the `/api/features` stub does not need to enable anything, and no E2E assertion is weakened. Happy to split this into its own PR if you would rather keep the diff clean — it just has to land somewhere for CI to go green.

**Comment by mattmillerai** [comment]
🤖 The reviews loop filed Linear follow-up ticket(s) for review thread(s) deferred as out of scope for this PR:
- [BE-10528](https://linear.app/comfyorg/issue/BE-10528) — Fix or remove unreachable free_tier_grant_state check in useEmailVerification — filed as `agent-spike` (premise unverified)

The following carry `agent-spike` instead of `agent-ok` because their reachability claim was not backed by evidence (BE-5378) — the claim is investigated before any code is written, and "the premise does not hold" is a valid, successful outcome:
- **Fix or remove unreachable free_tier_grant_state check in useEmailVerification** — no reachability block in the proposal

File: src/composables/auth/useEmailVerification.ts [hunk 14]
```diff
@@ -0,0 +1,199 @@
...
+      await user.reload()
+      reloadTick.value++
+
+      if (user.emailVerified) {
+        // Force a token refresh so subsequent API calls carry the
+        // `email_verified=true` claim, letting the backend lazily persist it.
+        await user.getIdToken(true)
+      }
+    } catch (error) {
+      console.error('Failed to refresh email verification status:', error)
```
[the remark this answers is not in the document]
Comment (mattmillerai) [reply src/composables/auth/useEmailVerification.ts]: Fixed in b7c70a99f1 — `console.error` replaced with `reportError(error, { errorType: 'email_verification_refresh_failure' })` from `@/platform/telemetry/reportError`, so the failure lands in Sentry/RUM under a stable `error_type` instead of only the console, and the raw Firebase error is no longer written to the console. Added a unit test asserting the reload rejection is reported and `refresh()` still resolves.

File: src/composables/auth/useEmailVerification.ts [hunk 15]
```diff
@@ -0,0 +1,199 @@
...
+
+/**
+ * `free_tier_grant_state` is not yet in the generated `BillingStatusResponse`
+ * (packages/ingest-types); the ingest billing-status endpoint doesn't return
+ * it yet either, so this narrows what's already an optional read rather than
+ * asserting a value. Drop this once the field lands in the generated type.
+ */
+type WithFreeTierGrantState = {
+  free_tier_grant_state?: 'verification_required' | 'deferred'
+}
```
[the remark this answers is not in the document]
Comment (mattmillerai) [reply src/composables/auth/useEmailVerification.ts]: Deferring this one to a follow-up rather than doing it here — the fix is not available in this repo.

`BillingStatusResponse` is generated code (`packages/ingest-types/src/types.gen.ts`) produced by `openapi-ts` from `packages/ingest-types/openapi.yaml`, and that spec file is not checked in — it comes from the ingest service. So "add the field to the endpoint and generated `BillingStatusResponse`" is a backend change to the billing-status contract first; the frontend can only regenerate after it lands. Nothing in this PR can make that happen.

The read stays correct in the meantime: `free_tier_grant_state` is typed optional, the composable falls through to the `generic` variant when it is absent, and `nudgeVariant` is behind the `email_verification_nudge_enabled` flag — so today's behaviour is the generic nudge, not a broken one. The narrowing type is deliberately scoped and documented with a drop-it-when-it-lands comment.

Recorded as a follow-up to add `free_tier_grant_state` to the billing-status response and then delete `WithFreeTierGrantState`. Resolving here since it is tracked.

**Comment by mattmillerai** [comment]
🤖 The reviews loop filed Linear follow-up ticket(s) for review thread(s) deferred as out of scope for this PR:
- [BE-10532](https://linear.app/comfyorg/issue/BE-10532) — Add free_tier_grant_state to the billing-status contract and drop the frontend narrowing type — filed as `agent-spike` (premise unverified)

The following carry `agent-spike` instead of `agent-ok` because their reachability claim was not backed by evidence (BE-5378) — the claim is investigated before any code is written, and "the premise does not hold" is a valid, successful outcome:
- **Add free_tier_grant_state to the billing-status contract and drop the frontend narrowing type** — no reachability block in the proposal

File: src/composables/auth/useEmailVerification.ts [hunk 16]
```diff
@@ -0,0 +1,202 @@
...
+      life: 5000
+    })
+    await refresh()
+  }
+
+  useEventListener(window, 'focus', () => {
+    // Gate on the underlying need, not the nudge's visibility: a dismissed
+    // generic nudge still needs to pick up a verification done in another tab.
+    if (needsEmailVerification.value) void refresh()
+  })
```
[the remark this answers is not in the document]
Comment (mattmillerai) [reply src/composables/auth/useEmailVerification.ts:169]: Fixed in 000cb94623. Extracted `isNudgeEnabled` (`isCloud && flags.emailVerificationNudgeEnabled`), used by both `nudgeVariant` and the focus listener, so a focus event no longer triggers `user.reload()` when the feature is off or outside cloud. The listener still gates on `needsEmailVerification` rather than `nudgeVariant`, so a dismissed nudge keeps picking up a verification done in another tab. Added a feature-off focus test (verified red before the fix, green after).

**Comment by mattmillerai** [comment]
@coderabbitai review

File: src/composables/auth/useEmailVerification.ts [hunk 17]
```diff
@@ -0,0 +1,206 @@
...
+    void reloadTick.value
+    const user = currentUser.value
+    if (!user) return false
+    if (user.emailVerified !== false) return false
+    return isPasswordUser.value
+  })
+
+  const freeTierVerificationRequired = computed(
+    () =>
+      (subscriptionStatus.value as WithFreeTierGrantState | null)
```
Comment (DrJKL) [inline src/composables/auth/useEmailVerification.ts]: This cast invents a field that the generated subscription contract does not expose. Remove the free-tier branch until the backend schema generates that state, or update the authoritative API schema first and consume the generated type.

File: src/composables/auth/useEmailVerification.test.ts [hunk 18]
```diff
@@ -0,0 +1,374 @@
+import { FirebaseError } from 'firebase/app'
+import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
+import { effectScope } from 'vue'
+import type { EffectScope } from 'vue'
+
+const mocks = vi.hoisted(() => ({
+  authStore: { currentUser: null as unknown },
```
Comment (DrJKL) [inline src/composables/auth/useEmailVerification.test.ts]: These `as unknown` initializers erase the mock contracts. Use explicitly typed mutable holders for the user and subscription values, or extract the nudge-state calculation into a pure typed function and test it directly.

**Review by DrJKL — CHANGES_REQUESTED** [review]
The nudge implementation and tests bypass generated and mock contracts with assertions.

File: src/composables/auth/useEmailVerification.ts (hunk 17 above)
Comment (mattmillerai) [reply src/composables/auth/useEmailVerification.ts]: Agreed — removed the free-tier branch (1e4cf16).

Checked before removing: `subscriptionStatus` is `ref<BillingStatusResponse | null>` and is only ever filled from `workspaceApi.getBillingStatus()`, and the generated ingest `BillingStatusResponse` has no `free_tier_grant_state`. The only generated type that does expose it is the registry `GetCloudSubscriptionStatus` response, which has no call site in `src/`. So the `credits` variant was unreachable, not just untyped.

`nudgeVariant` therefore collapses to an `isNudgeVisible` boolean; `creditsMessage` and the `useSubscription` dependency are gone. Left a note for re-adding the credit-specific copy once the billing-status schema actually generates the field.

File: src/composables/auth/useEmailVerification.test.ts (hunk 18 above)
Comment (mattmillerai) [reply src/composables/auth/useEmailVerification.test.ts]: Fixed in 1e4cf16. The subscription holder is gone entirely (the free-tier branch it fed was removed), and the user holder is now explicitly typed: `authStore: { currentUser: null as FakeUser | null }`. No `as unknown` left in the file.

**Comment by mattmillerai** [comment]
🤖 The reviews loop filed Linear follow-up ticket(s) for review thread(s) deferred as out of scope for this PR:
- [BE-11402](https://linear.app/comfyorg/issue/BE-11402) — Re-add the credit-specific email-verification nudge once billing status exposes free_tier_grant_state — filed as `agent-spike` (premise unverified)

The following carry `agent-spike` instead of `agent-ok` because their reachability claim was not backed by evidence (BE-5378) — the claim is investigated before any code is written, and "the premise does not hold" is a valid, successful outcome:
- **Re-add the credit-specific email-verification nudge once billing status exposes free_tier_grant_state** — no reachability block in the proposal
