### PR TITLE
fix(errors): keep missing node packs across prompt submissions

### PR DESCRIPTION
**Pull request by jaeone94**
The original thesis of #14251, and nothing else. **10 production lines added, 10 removed.**

## What

Missing node packs were wiped from the Issues panel on every prompt submission, while missing model and media state was deliberately preserved. This aligns node packs with the other two.

A submission carries no information about whether a node pack is installed. The missing node can sit on a branch the run never touches, and installing a pack needs a backend restart either way.

## Why it started mattering

#14177 replaced the Run-button warning icon's independent derivation with a store read:

```diff
-const hasMissingNodes = computed(() => graphHasMissingNodes(app.rootGraph, nodeDefStore.nodeDefsByName))
+const { hasMissingError } = storeToRefs(useExecutionErrorStore())
```

Before that the icon re-derived from the graph on every access, so clearing on submit could not affect it. After it, the icon is a pure read of `missingNodeTypes`, and the submit-time wipe started flipping the Run button from `triangle-alert` back to `play` on the first submission.

Blame also shows the clear was an omission rather than a decision: the commit that introduced missing-node state added it in the same stroke with no comment and no test, and the `clearAllErrors()` call in `queuePrompt` predates missing-node state by ~20 months.

## Changes

- `clearAllErrors` renamed to `clearRunErrors`. It clears the three categories this store owns — execution, prompt and node errors — and no longer touches missing-node state or overlay visibility. The name now matches what it does.
- `ComfyApp.clean()` spells out what it used to get transitively: the missing-node clear and the overlay dismissal. **Its net behaviour is unchanged** — all eight effects are preserved, only the ordering of two inert steps differs.

The single intended behaviour change is at `queuePrompt`.

## Why the overlay dismissal moved rather than disappeared

Leaving `isErrorOverlayOpen = false` in `clearRunErrors` would have been actively wrong once missing-node state survives: `hasAnyError` stays true while the overlay closes, which flips `showErrorIndicatorOnPanelButton` (`TopMenuSection.vue:274`) from false to true. A red indicator would appear as a side effect of pressing Run. `MobileDisplay.vue` also reads the flag raw, with no error-count guard.

## Ordering

**#14555 first, but as a quality improvement rather than a prerequisite.** (Corrected after review — the original wording overstated this.)

API-JSON entries are bare strings (`app.ts:2202`), so `removeMissingNodesByNodeId` and `removeMissingNodesByPrefix` cannot touch them, and `removeMissingNodesByType` is unreachable because `replaceNodesInPlace` walks live graph nodes that were never instantiated. #14555 gives those entries a `nodeId`, which makes the existing removers work.

They are not unclearable without it, though. `clean()` — which this PR teaches to call `setMissingNodeTypes([])` — is reachable from `Comfy.ClearWorkflow` (`useCoreCommands.ts:278`), the Clear button (`ui.ts:674`) and `loadGraphData(clean=true)`; switching or opening a workflow runs `showPendingWarnings`, which clears when empty.

So the accurate framing: within the currently-open API-JSON graph, submission was the only in-place clearer, and after this lands you have to discard or switch the workflow to shed the row. A bounded UX regression, not a permanent leak.

#14556 is independent of both, and has already merged.

## Verification

3 unit tests, mutation-proved. `clean()` parity against the merge base checked effect by effect. No `clearAllErrors` reference remains anywhere in the tree. typecheck, lint, format, knip clean; the full unit suite's failures reproduce identically at the merge base.

## Related

- Replaces #14251 (closed), which grew to ~600 non-test lines by absorbing three adjacent concerns. Split into #14555, #14556 and this.

### CODE REVIEW

**Comment by jaeone94** [comment]
> `clearRunErrors()` deliberately preserves missing-model and missing-media state. Lines 2411-2413 only clear missing nodes. A direct `clean()` call **can now** retain stale missing model or media warnings and their error counts.

Not a regression — `clean()` never cleared those, and the suggested fix would break the tab-switch path.

**`clean()` is at parity with the base.** At `82f8ebd6b7`, `clearAllErrors()` was:

```js
function clearAllErrors() {
  lastExecutionError.value = null
  lastPromptError.value = null
  lastNodeErrors.value = null
  missingNodesStore.setMissingNodeTypes([])
  isErrorOverlayOpen.value = false
}
```

This PR splits that into `clearRunErrors()` + `dismissErrorOverlay()` + `setMissingNodeTypes([])` at the `clean()` call site — the same set of effects. `executionErrorStore` has never referenced `clearMissingModels` or `clearMissingMedia`, before or after. The "now" in the finding does not hold.

**Missing model/media clearing already happens, six lines above `clean()`** (`app.ts:1225-1237`):

```js
if (skipAssetScans) {
  useMissingModelStore().createVerificationAbortController().abort()
  useMissingMediaStore().createVerificationAbortController().abort()
  useMissingModelStore().setMissingModels([])
  useMissingMediaStore().setMissingMedia([])
} else {
  useMissingModelStore().clearMissingModels()
  useMissingMediaStore().clearMissingMedia()
}

if (clean !== false) {
  this.canvas.setGraph(this.rootGraph)
  this.clean()
}
```

**The proposed patch would regress the `skipAssetScans` branch.** The two calls are not interchangeable:

- `setMissingModels([])` clears only `missingModelCandidates`.
- `clearMissingModels()` additionally wipes `fileSizes`, `gatedRepoUrls`, `folderPaths`, `modelExpandState`, `selectedLibraryModel` and `importTaskIds`.

On a workflow tab switch (`skipAssetScans: true`), the branch deliberately takes the narrow clear so cached results restored by `showPendingWarnings` still display their file sizes. Putting `clearMissingModels()` inside `clean()` — which runs immediately afterwards — would destroy that state on the next line, nullifying the reason the branch exists.

Not applying. If missing model/media clearing should move into `clean()`, that is a change to the `skipAssetScans` contract and belongs in its own PR with the tab-switch case covered.

**Comment by jaeone94** [comment]
**Integration note: merging this after #14555 needs one import restored, and git will not flag it.**

Found while building a local A1+A3 tree. `git merge` resolves `src/scripts/app.ts` with **no conflict**, and the result does not compile:

```
src/scripts/app.ts(2475,5): error TS2304: Cannot find name 'useMissingNodesErrorStore'.
```

The cause is a clean semantic conflict:

| tree | `import { useMissingNodesErrorStore }` | usages |
|---|---|---|
| merge base `82f8ebd6b7` | present (line 86) | `showMissingNodesError` |
| #14555 (A1) | **removed** — A1 replaced that usage with the `pendingWarnings` path | none |
| #14557 (this PR) | present | `showMissingNodesError` + **new one in `clean()`** |
| merged | **absent** | `clean()` usage survives |

Git takes A1's deletion of the import line and this PR's addition of the `clean()` call, and neither side edited a line the other touched — so there is nothing to conflict on. Each PR is correct and green on its own; only the union is broken.

**Handling:** whichever of the two lands second must be updated from `main` before merge, and the rebase needs the import added back. CI on the updated branch catches it (`pnpm typecheck` fails as above), so this is safe as long as the branch is not merged stale. Flagging it because a green check on this PR today does not mean the post-merge tree is green.

No code change here — both branches are individually correct, and pre-adding an unused import to #14555 would fail `knip`/lint there.

File: src/scripts/app.ts [hunk 1]
```diff
@@ -2408,7 +2408,9 @@ export class ComfyApp {
     const nodeOutputStore = useNodeOutputStore()
     nodeOutputStore.resetAllOutputsAndPreviews()
     const executionErrorStore = useExecutionErrorStore()
-    executionErrorStore.clearAllErrors()
+    executionErrorStore.clearRunErrors()
+    executionErrorStore.dismissErrorOverlay()
+    useMissingNodesErrorStore().setMissingNodeTypes([])
```
Comment (christian-byrne) [inline src/scripts/app.ts:2437]: issue (blocking): this PR and #14555 auto-merge `app.ts` into a tree that does not compile.

#14555 removes the `useMissingNodesErrorStore` import at `app.ts:86` when it rewrites `showMissingNodesError`, because that was the last use. This PR adds a new use here. Git merges both hunks with no conflict.

I ran it. Merge #14555 into `main`, then this branch, resolve only the `app.test.ts` conflict, then `pnpm typecheck`:

```
src/scripts/app.ts(2435,5): error TS2304: Cannot find name 'useMissingNodesErrorStore'.
```

`app.test.ts` does conflict, so a manual rebase forces someone to look. But a merge-queue or merge-commit path that resolves only the test file ships a non-compiling `app.ts`. Whoever lands second needs to re-add that import, and the order does not matter.

File: src/scripts/app.ts [hunk 2]
```diff
@@ -1685,7 +1685,7 @@ export class ComfyApp {
     const executionStore = useExecutionStore()
     const executionErrorStore = useExecutionErrorStore()
     const telemetry = useTelemetry()
-    executionErrorStore.clearAllErrors()
+    executionErrorStore.clearRunErrors()
```
Comment (christian-byrne) [inline src/scripts/app.ts:1649]: issue: `queuePrompt` no longer dismisses the error overlay, and mobile linear mode reads that flag raw.

On main, `clearAllErrors()` here set `isErrorOverlayOpen = false` on every submit. `clearRunErrors` does not, and the dismissal was added only to `clean()`.

Desktop is fine: `useErrorOverlayState.ts:202-207` gates `isVisible` on `totalErrorCount > 0`, so a stale-true flag renders nothing. But `MobileDisplay.vue:223` and `:257` read the flag directly, with `LinearPreview` in the `v-else`:

```vue
<MobileError v-if="executionErrorStore.isErrorOverlayOpen" />
<LinearPreview v-else mobile ... />
```

So after a run fails and the overlay opens, tapping Run clears the three error refs and leaves the flag true. `MobileError` keeps rendering with nothing in it, `LinearPreview` never appears, and the tab-1 indicator stays lit. It self-heals only when `execution_start` arrives, which is the whole queue wait for a job behind others, and never if the user cancels first.

Restoring the dismissal here would reintroduce the bug this PR fixes, so gating those two `MobileDisplay` reads on `useErrorOverlayState().isVisible` looks like the right direction instead.

File: src/stores/executionErrorStore.ts [hunk 3]
```diff
@@ -83,16 +83,14 @@ export const useExecutionErrorStore = defineStore('executionError', () => {
     isErrorOverlayOpen.value = false
   }
 
-  /** Clear all error state.
-   *  Missing model state is intentionally preserved here to avoid wiping
-   *  in-progress model repairs (importTaskIds, URL inputs, etc.).
-   *  Missing models are cleared separately during workflow load/clean paths. */
-  function clearAllErrors() {
+  /** Clear errors tied to the previous run: execution, prompt, and node errors.
```
Comment (christian-byrne) [inline src/stores/executionErrorStore.ts:86]: suggestion (non-blocking): this comment is not accurate for group-node entries.

"Missing nodes are cleared by `ComfyApp.clean` and the graph error-clearing hooks" holds for entries carrying a `nodeId`. Group nodes do not: `groupNode.ts:778` and `:783` push `{type, hint}` and `{type, action}` with no `nodeId` via the `beforeConfigureGraph` hook, so `removeMissingNodesByNodeId` and `removeMissingNodesByPrefix` both skip them by design and only the full-overwrite paths clear them.

This PR's own `clean` test seeds `setMissingNodeTypes(['MissingGroupNode'])`, so the shape is already in view. Narrowing the sentence to the overwrite paths would keep the comment true.

**Review by christian-byrne — COMMENTED** [review]
Reviewed the diff and traced the `clean()` parity claim myself rather than taking it. It holds: effect for effect, nothing is dropped or duplicated, only the missing-node and overlay writes swap order, and both are plain ref assignments that nothing observes in between (`dismissErrorOverlay` reads nothing; the one watcher on `missingNodesError` is default `flush:'pre'`). Both former `clearAllErrors` call sites are migrated and no reference remains anywhere in the tree.

The unit tests are strong. I re-ran mutations against every production line the PR touches and all of them are killed, including the two single-effect variants (re-adding only the overlay reset, or only `setMissingNodeTypes([])`). `executionErrorStore.test.ts` is not a mechanical rename: it inverts three assertions and is the only thing pinning that `clearRunErrors` leaves the overlay alone.

One finding could not be anchored inline because it is about the PR description rather than a diff line:

**note (non-blocking): the "Ordering" section is stronger than what I could confirm.**

"Landing this one alone would strand them" overstates it. The first half holds: API-JSON entries are bare strings (`app.ts:2202`), so `removeMissingNodesByNodeId` and `removeMissingNodesByPrefix` genuinely cannot touch them, and `removeMissingNodesByType` is unreachable for them because `replaceNodesInPlace` walks live graph nodes that were never instantiated.

But they are not unclearable. `clean()`, which this PR teaches to call `setMissingNodeTypes([])`, is reachable from `Comfy.ClearWorkflow` (`useCoreCommands.ts:278`), the Clear button (`ui.ts:674`), and `loadGraphData(clean=true)`. Switching or opening a workflow runs `showPendingWarnings`, which clears when empty. `rescanAndSurfaceMissingNodes` yields `[]` for API JSON.

Accurate framing looks like: within the currently-open API-JSON graph, submission was the only in-place clearer, so after this lands you have to discard or switch the workflow to shed the row. Bounded UX regression rather than a permanent leak, which makes #14555 a quality improvement to land first rather than a correctness prerequisite.

File: src/scripts/app.test.ts [hunk 4]
```diff
@@ -219,6 +221,34 @@ describe('ComfyApp', () => {
       vi.spyOn(api, 'dispatchCustomEvent').mockImplementation(() => true)
     }
 
+    it('preserves missing node packs when submitting a prompt', async () => {
```
Comment (christian-byrne) [inline src/scripts/app.test.ts:315]: suggestion (non-blocking): the user-visible bug has no e2e.

The unit tests pin the store and `queuePrompt` well; I re-ran mutations on every production line this PR touches and all are killed. But the thing a user reports, missing node packs disappearing from the Errors tab when they press Run, is only covered at the store level.

`browser_tests/tests/propertiesPanel/errorsTabMissingNodes.spec.ts` already exists and is the natural home: load a workflow with a missing pack, submit, assert the panel is still populated. That is the assertion that would survive a future refactor moving the clear somewhere else entirely.

**Comment by jaeone94** [comment]
Replaced by #14900 — same thesis, rebased onto `main` and narrowed.

Thanks for the review here; all of it carried over. The blocking finding — that this branch and #14555 auto-merge `app.ts` into a tree that does not compile — is resolved: #14555 landed, this was rebased onto it, and the `useMissingNodesErrorStore` import is restored. Your other three are handled too:

- **`queuePrompt` no longer dismissing the overlay.** You were right that `MobileDisplay` reads the flag raw and would render an empty `MobileError`. `clearRunErrors` keeps `isErrorOverlayOpen.value = false`, so submission still dismisses it — the split that dropped it is gone.
- **The `clearRunErrors` comment and group nodes.** The comment no longer claims the hooks clear missing nodes generally; group-node entries carry no `nodeId` (`groupNode.ts:778`, `:783`) and only the overwrite paths reach them.
- **No e2e for the user-visible bug.** Added to `errorsTabMissingNodes.spec.ts`, and it waits on the `POST /api/prompt` response before re-asserting so it observes the state after the submit path rather than racing it.
- **The "Ordering" overstatement.** Corrected — your framing was right, and the replacement PR does not repeat the claim.

The one substantive difference: #14900 is deliberately narrower than this branch. An intermediate version generalised the rule to the missing-model and missing-media stores. Three independent unbriefed reviews found five defects in that generalisation — those two stores carry async verification that outlives the graph that started it, a per-workflow cache, and a two-tier repair state, none of which missing nodes have. That work is written up and will be its own change; #14900 fixes the reported bug in four production lines and leaves models and media exactly as they are.
