### ISSUE TITLE
[Bug]: Comfyui keeps loading. -> Bug on the latest version v1.5.8

### ISSUE THREAD

**Issue by Cedri4** [Comfy-Org/ComfyUI_frontend#1834]
### Frontend Version

So yesterday with v1.5.7 it worked fine.
When I updated to v1.5.8, it didn't work.
EDIT: But now that I try again v1.5.7 also doesn't work for me probably the new comfy version

### Expected Behavior

Comfyui loading correctly.
Not like this:
https://github.com/user-attachments/assets/fe31acf7-da6f-4050-8994-8dc0300af0e6

### Actual Behavior

https://github.com/user-attachments/assets/fe31acf7-da6f-4050-8994-8dc0300af0e6

### Steps to Reproduce

Update your comfy to v1.5.8

### Debug Logs

```powershell
This is the important part that I found that talks about this custom node:

FizzleDorf Custom Nodes: Loaded
Traceback (most recent call last):
  File "C:\Users\gerar\Documents\comfy\ComfyUI\nodes.py", line 2037, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\gerar\\Documents\\comfy\\ComfyUI\\custom_nodes\\ComfyUI_frontend\\__init__.py'

Cannot import C:\Users\gerar\Documents\comfy\ComfyUI\custom_nodes\ComfyUI_frontend module for custom nodes: [Errno 2] No such file or directory: 'C:\\Users\\gerar\\Documents\\comfy\\ComfyUI\\custom_nodes\\ComfyUI_frontend\\__init__.py'
# 😺dzNodes: LayerStyle -> Cannot import name 'guidedFilter' from 'cv2.ximgproc'
A few nodes cannot works properly, while most nodes are not affected. Please REINSTALL package 'opencv-contrib-python'.
For detail refer to https://github.com/chflame163/ComfyUI_LayerStyle/issues/5
[MaraScott] Loaded
```

### Browser Logs

![image](https://github.com/user-attachments/assets/053c76db-a90f-49e8-9abf-69092656c0ac)

### Setting JSON

[comfy.settings.json](https://github.com/user-attachments/files/18047917/comfy.settings.json)

### Other

Without --front-end-version Comfy-Org/ComfyUI_frontend@latest, it worked just fine, so the error is definitely on the latest version.

**Comment by Cedri4** [comment]
I forgot this part:
What browsers do you use to access the UI ?

- Opera, brave, google chrome doesn't work.

**Comment by zjf2671** [comment]
This is a serious problem. After working on it all afternoon today, I thought it was a problem with the plug-in I downloaded. Later, I could just revert to the previous version 1.5.7

**Comment by EasyComfyui** [comment]
same +1, A custom node caused the error

**Comment by webfiltered** [comment]
Reproduced on my end.  Until this is resolved, you can either disable `mtb` or use frontend <= v1.5.7

**Comment by melMass** [comment]
My fault I pushed a file by mistake for an upcoming thing I'm working on!
Thanks for the heads up @webfiltered <3

**Comment by melMass** [comment]
I think the issue is something related to i18n
![image](https://github.com/user-attachments/assets/667458cc-dea0-4d5c-b268-f88b3ea10ce1)
