### PR TITLE
[Bug] Fix uuid generation in insecure context

### LINKED ISSUE #3498: [Bug]: useErrorHandling.ts:8  TypeError: crypto.randomUUID is not a function
### Frontend Version

[ComfyUI 0.3.29](https://github.com/comfyanonymous/ComfyUI)
[ComfyUI_frontend v1.16.8](https://github.com/Comfy-Org/ComfyUI_frontend)

### Expected Behavior

fix..

### Actual Behavior

error

### Steps to Reproduce

I have removed all the plugins
Image

Then start Comfyui, as shown in the picture

Image
Open any workflow randomly

save as
Image

Image

Image

Image

Image

Image

Image

The key part is coming up.

Image

Open any non empty workflow randomly
Image

Image

Image

### Debug Logs

```powershell
Only the frontend reported an error, the backend terminal did not have an error
```

### Browser Logs

useErrorHandling.ts:8 
 TypeError: crypto.randomUUID is not a function
    at Object.saveWorkflowAs (workflowService.ts:98:25)
    at async function (useCoreCommands.ts:104:15)
    at async useErrorHandling.ts:40:16
    at async Proxy.execute (commandStore.ts:96:7)
toastErrorHandler	@	useErrorHandling.ts:8
(匿名)	@	useErrorHandling.ts:42
await in (匿名)		
execute	@	commandStore.ts:96
command	@	menuItemStore.ts:55

### Setting JSON

{
    "Comfy.UseNewMenu": "Top",
    "LiteGraph.Canvas.MaximumFps": 120,
    "Comfy.LinkRenderMode": 1,
    "Comfy.CustomColorPalettes": {
        "obsidian": {
            "version": 111,
            "id": "obsidian",
            "name": "Obsidian",
            "colors": {
                "node_slot": {
                    "CLIP": "#FFD500",
                    "CLIP_VISION": "#A8DADC",
                    "CLIP_VISION_OUTPUT": "#ad7452",
                    "CONDITIONING": "#FFA931",
                    "CONTROL_NET": "#6EE7B7",
                    "IMAGE": "#64B5F6",
                    "LATENT": "#FF9CF9",
                    "MASK": "#81C784",
                    "MODEL": "#B39DDB",
                    "STYLE_MODEL": "#C2FFAE",
                    "VAE": "#FF6E6E",
                    "TAESD": "#DCC274",
                    "PIPE_LINE": "#7737AA",
                    "PIPE_LINE_SDXL": "#7737AA",
                    "INT": "#29699C",
                    "X_Y": "#38291f",
                    "XYPLOT": "#74DA5D",
                    "LORA_STACK": "#94dccd",
                    "CONTROL_NET_STACK": "#94dccd",
                    "FAST_MODEL_LOADER": "#ffd399",
                    "SAMPLING": "#60a5fa"
                },
                "litegraph_base": {
                    "BACKGROUND_IMAGE": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAQBJREFUeNrs1rEKwjAUhlETUkj3vP9rdmr1Ysammk2w5wdxuLgcMHyptfawuZX4pJSWZTnfnu/lnIe/jNNxHHGNn//HNbbv+4dr6V+11uF527arU7+u63qfa/bnmh8sWLBgwYJlqRf8MEptXPBXJXa37BSl3ixYsGDBMliwFLyCV/DeLIMFCxYsWLBMwSt4Be/NggXLYMGCBUvBK3iNruC9WbBgwYJlsGApeAWv4L1ZBgsWLFiwYJmCV/AK3psFC5bBggULloJX8BpdwXuzYMGCBctgwVLwCl7Be7MMFixYsGDBsu8FH1FaSmExVfAxBa/gvVmwYMGCZbBg/W4vAQYA5tRF9QYlv/QAAAAASUVORK5CYII=",
                    "CLEAR_BACKGROUND_COLOR": "#222222",
                    "NODE_TITLE_COLOR": "#d4d4d8",
                    "NODE_SELECTED_TITLE_COLOR": "#ffffff",
                    "NODE_TEXT_SIZE": 14,
                    "NODE_TEXT_COLOR": "#ffffff",
                    "NODE_SUBTEXT_SIZE": 12,
                    "NODE_DEFAULT_COLOR": "#09090b",
                    "NODE_DEFAULT_BGCOLOR": "rgba(24,24,27,.9)",
                    "NODE_DEFAULT_BOXCOLOR": "rgba(255,255,255,.75)",
                    "NODE_DEFAULT_SHAPE": 2,
                    "NODE_BOX_OUTLINE_COLOR": "#60a5fa",
                    "DEFAULT_SHADOW_COLOR": "rgba(0,0,0,0)",
                    "DEFAULT_GROUP_FONT": 24,
                    "WIDGET_BGCOLOR": "#242427",
                    "WIDGET_OUTLINE_COLOR": "#3f3f46",
                    "WIDGET_TEXT_COLOR": "#d4d4d8",
                    "WIDGET_SECONDARY_TEXT_COLOR": "#d4d4d8",
                    "LINK_COLOR": "#9A9",
                    "EVENT_LINK_COLOR": "#A86",
                    "CONNECTING_LINK_COLOR": "#AFA"
                },
                "comfy_base": {
                    "fg-color": "#fff",
                    "bg-color": "#09090b",
                    "comfy-menu-bg": "rgba(24,24,24,.9)",
                    "comfy-input-bg": "#262626",
                    "input-text": "#ddd",
                    "descrip-text": "#999",
                    "drag-text": "#ccc",
                    "error-text": "#ff4444",
                    "border-color": "#29292c",
                    "tr-even-bg-color": "rgba(28,28,28,.9)",
                    "tr-odd-bg-color": "rgba(19,19,19,.9)"
                }
            }
        },
        "obsidian_dark": {
            "version": 111,
            "id": "obsidian_dark",
            "name": "Obsidian Dark",
            "colors": {
                "node_slot": {
                    "CLIP": "#FFD500",
                    "CLIP_VISION": "#A8DADC",
                    "CLIP_VISION_OUTPUT": "#ad7452",
                    "CONDITIONING": "#FFA931",
                    "CONTROL_NET": "#6EE7B7",
                    "IMAGE": "#64B5F6",
                    "LATENT": "#FF9CF9",
                    "MASK": "#81C784",
                    "MODEL": "#B39DDB",
                    "STYLE_MODEL": "#C2FFAE",
                    "VAE": "#FF6E6E",
                    "TAESD": "#DCC274",
                    "PIPE_LINE": "#7737AA",
                    "PIPE_LINE_SDXL": "#7737AA",
                    "INT": "#29699C",
                    "X_Y": "#38291f",
                    "XYPLOT": "#74DA5D",
                    "LORA_STACK": "#94dccd",
                    "CONTROL_NET_STACK": "#94dccd",
                    "FAST_MODEL_LOADER": "#ffd399",
                    "SAMPLING": "#60a5fa"
                },
                "litegraph_base": {
                    "BACKGROUND_IMAGE": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAAAACXBIWXMAAAsTAAALEwEAmpwYAAAGlmlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgOS4xLWMwMDEgNzkuMTQ2Mjg5OSwgMjAyMy8wNi8yNS0yMDowMTo1NSAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczpkYz0iaHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8iIHhtbG5zOnBob3Rvc2hvcD0iaHR0cDovL25zLmFkb2JlLmNvbS9waG90b3Nob3AvMS4wLyIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0RXZ0PSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VFdmVudCMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIDI1LjEgKFdpbmRvd3MpIiB4bXA6Q3JlYXRlRGF0ZT0iMjAyMy0xMS0xM1QwMDoxODowMiswMTowMCIgeG1wOk1vZGlmeURhdGU9IjIwMjMtMTEtMTVUMDI6MDQ6NTkrMDE6MDAiIHhtcDpNZXRhZGF0YURhdGU9IjIwMjMtMTEtMTVUMDI6MDQ6NTkrMDE6MDAiIGRjOmZvcm1hdD0iaW1hZ2UvcG5nIiBwaG90b3Nob3A6Q29sb3JNb2RlPSIzIiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOmIyYzRhNjA5LWJmYTctYTg0MC1iOGFlLTk3MzE2ZjM1ZGIyNyIgeG1wTU06RG9jdW1lbnRJRD0iYWRvYmU6ZG9jaWQ6cGhvdG9zaG9wOjk0ZmNlZGU4LTE1MTctZmQ0MC04ZGU3LWYzOTgxM2E3ODk5ZiIgeG1wTU06T3JpZ2luYWxEb2N1bWVudElEPSJ4bXAuZGlkOjIzMWIxMGIwLWI0ZmItMDI0ZS1iMTJlLTMwNTMwM2NkMDdjOCI+IDx4bXBNTTpIaXN0b3J5PiA8cmRmOlNlcT4gPHJkZjpsaSBzdEV2dDphY3Rpb249ImNyZWF0ZWQiIHN0RXZ0Omluc3RhbmNlSUQ9InhtcC5paWQ6MjMxYjEwYjAtYjRmYi0wMjRlLWIxMmUtMzA1MzAzY2QwN2M4IiBzdEV2dDp3aGVuPSIyMDIzLTExLTEzVDAwOjE4OjAyKzAxOjAwIiBzdEV2dDpzb2Z0d2FyZUFnZW50PSJBZG9iZSBQaG90b3Nob3AgMjUuMSAoV2luZG93cykiLz4gPHJkZjpsaSBzdEV2dDphY3Rpb249InNhdmVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOjQ4OWY1NzlmLTJkNjUtZWQ0Zi04OTg0LTA4NGE2MGE1ZTMzNSIgc3RFdnQ6d2hlbj0iMjAyMy0xMS0xNVQwMjowNDo1OSswMTowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIDI1LjEgKFdpbmRvd3MpIiBzdEV2dDpjaGFuZ2VkPSIvIi8+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJzYXZlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDpiMmM0YTYwOS1iZmE3LWE4NDAtYjhhZS05NzMxNmYzNWRiMjciIHN0RXZ0OndoZW49IjIwMjMtMTEtMTVUMDI6MDQ6NTkrMDE6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCAyNS4xIChXaW5kb3dzKSIgc3RFdnQ6Y2hhbmdlZD0iLyIvPiA8L3JkZjpTZXE+IDwveG1wTU06SGlzdG9yeT4gPC9yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz4OTe6GAAAAx0lEQVR42u3WMQoAIQxFwRzJys77X8vSLiRgITif7bYbgrwYc/mKXyBoY4VVBgsWLFiwYFmOlTv+9jfDOjHmr8u6eVkGCxYsWLBgmc5S8ApewXvgYRksWLBgKXidpeBdloL3wMOCBctgwVLwCl7BuyyDBQsWLFiwTGcpeAWv4D3wsAwWLFiwFLzOUvAuS8F74GHBgmWwYCl4Ba/gXZbBggULFixYprMUvIJX8B54WAYLFixYCl5nKXiXpeA98LBgwTJYsGC9tg1o8f4TTtqzNQAAAABJRU5ErkJggg==",
                    "CLEAR_BACKGROUND_COLOR": "#09090b",
                    "NODE_TITLE_COLOR": "#d4d4d8",
                    "NODE_SELECTED_TITLE_COLOR": "#ffffff",
                    "NODE_TEXT_SIZE": 14,
                    "NODE_TEXT_COLOR": "#ffffff",
                    "NODE_SUBTEXT_SIZE": 12,
                    "NODE_DEFAULT_COLOR": "#09090b",
                    "NODE_DEFAULT_BGCOLOR": "rgba(24,24,27,.9)",
                    "NODE_DEFAULT_BOXCOLOR": "rgba(255,255,255,.75)",
                    "NODE_DEFAULT_SHAPE": 2,
                    "NODE_BOX_OUTLINE_COLOR": "#60a5fa",
                    "DEFAULT_SHADOW_COLOR": "rgba(0,0,0,0)",
                    "DEFAULT_GROUP_FONT": 24,
                    "WIDGET_BGCOLOR": "#242427",
                    "WIDGET_OUTLINE_COLOR": "#3f3f46",
                    "WIDGET_TEXT_COLOR": "#d4d4d8",
                    "WIDGET_SECONDARY_TEXT_COLOR": "#d4d4d8",
                    "LINK_COLOR": "#9A9",
                    "EVENT_LINK_COLOR": "#A86",
                    "CONNECTING_LINK_COLOR": "#AFA"
                },
                "comfy_base": {
                    "fg-color": "#fff",
                    "bg-color": "#09090b",
                    "comfy-menu-bg": "rgba(24,24,24,.9)",
                    "comfy-input-bg": "#262626",
                    "input-text": "#ddd",
                    "descrip-text": "#999",
                    "drag-text": "#ccc",
                    "error-text": "#ff4444",
                    "border-color": "#29292c",
                    "tr-even-bg-color": "rgba(28,28,28,.9)",
                    "tr-odd-bg-color": "rgba(19,19,19,.9)"
                }
            }
        },
        "milk_white": {
            "id": "milk_white",
            "name": "Milk White",
            "colors": {
                "node_slot": {
                    "CLIP": "#FFA726",
                    "CLIP_VISION": "#5C6BC0",
                    "CLIP_VISION_OUTPUT": "#8D6E63",
                    "CONDITIONING": "#EF5350",
                    "CONTROL_NET": "#66BB6A",
                    "IMAGE": "#42A5F5",
                    "LATENT": "#AB47BC",
                    "MASK": "#9CCC65",
                    "MODEL": "#7E57C2",
                    "STYLE_MODEL": "#D4E157",
                    "VAE": "#FF7043",
                    "PIPE_LINE": "#7737AA",
                    "PIPE_LINE_SDXL": "#7737AA",
                    "INT": "#29699C",
                    "X_Y": "#38291f",
                    "XYPLOT": "#74DA5D",
                    "LORA_STACK": "#94dccd",
                    "CONTROL_NET_STACK": "#94dccd",
                    "FAST_MODEL_LOADER": "#ffd399",
                    "SAMPLING": "#60a5fa"
                },
                "litegraph_base": {
                    "BACKGROUND_IMAGE": "data:image/gif;base64,R0lGODlhZABkALMAAAAAAP///+vr6+rq6ujo6Ofn5+bm5uXl5d3d3f///wAAAAAAAAAAAAAAAAAAAAAAACH5BAEAAAkALAAAAABkAGQAAAT/UMhJq7046827HkcoHkYxjgZhnGG6si5LqnIM0/fL4qwwIMAg0CAsEovBIxKhRDaNy2GUOX0KfVFrssrNdpdaqTeKBX+dZ+jYvEaTf+y4W66mC8PUdrE879f9d2mBeoNLfH+IhYBbhIx2jkiHiomQlGKPl4uZe3CaeZifnnijgkESBqipqqusra6vsLGys62SlZO4t7qbuby7CLa+wqGWxL3Gv3jByMOkjc2lw8vOoNSi0czAncXW3Njdx9Pf48/Z4Kbbx+fQ5evZ4u3k1fKR6cn03vHlp7T9/v8A/8Gbp4+gwXoFryXMB2qgwoMMHyKEqA5fxX322FG8tzBcRnMW/zlulPbRncmQGidKjMjyYsOSKEF2FBlJQMCbOHP6c9iSZs+UnGYCdbnSo1CZI5F64kn0p1KnTH02nSoV3dGTV7FFHVqVq1dtWcMmVQZTbNGu72zqXMuW7danVL+6e4t1bEy6MeueBYLXrNO5Ze36jQtWsOG97wIj1vt3St/DjTEORss4nNq2mDP3e7w4r1bFkSET5hy6s2TRlD2/mSxXtSHQhCunXo26NevCpmvD/UU6tuullzULH76q92zdZG/Ltv1a+W+osI/nRmyc+fRi1Xdbh+68+0vv10dH3+77KD/i6IdnX669/frn5Zsjh4/2PXju8+8bzc9/6fj27LFnX11/+IUnXWl7BJfegm79FyB9JOl3oHgSklefgxAC+FmFGpqHIYcCfkhgfCohSKKJVo044YUMttggiBkmp6KFXw1oII24oYhjiDByaKOOHcp3Y5BD/njikSkO+eBREQAAOw==",
                    "CLEAR_BACKGROUND_COLOR": "lightgray",
                    "NODE_TITLE_COLOR": "#222",
                    "NODE_SELECTED_TITLE_COLOR": "#000",
                    "NODE_TEXT_SIZE": 14,
                    "NODE_TEXT_COLOR": "#444",
                    "NODE_SUBTEXT_SIZE": 12,
                    "NODE_DEFAULT_COLOR": "#F7F7F7",
                    "NODE_DEFAULT_BGCOLOR": "#F5F5F5",
                    "NODE_DEFAULT_BOXCOLOR": "#555",
                    "NODE_DEFAULT_SHAPE": 2,
                    "NODE_BOX_OUTLINE_COLOR": "#000",
                    "DEFAULT_SHADOW_COLOR": "rgba(0,0,0,0.1)",
                    "DEFAULT_GROUP_FONT": 24,
                    "WIDGET_BGCOLOR": "#D4D4D4",
                    "WIDGET_OUTLINE_COLOR": "#999",
                    "WIDGET_TEXT_COLOR": "#222",
                    "WIDGET_SECONDARY_TEXT_COLOR": "#555",
                    "LINK_COLOR": "#9A9",
                    "EVENT_LINK_COLOR": "#FF9800",
                    "CONNECTING_LINK_COLOR": "#222"
                },
                "comfy_base": {
                    "fg-color": "#222",
                    "bg-color": "#DDD",
                    "comfy-menu-bg": "#F5F5F5",
                    "comfy-input-bg": "#C9C9C9",
                    "input-text": "#222",
                    "descrip-text": "#444",
                    "drag-text": "#555",
                    "error-text": "#F44336",
                    "border-color": "#bbb",
                    "tr-even-bg-color": "#f9f9f9",
                    "tr-odd-bg-color": "#fff",
                    "content-bg": "#e0e0e0",
                    "content-fg": "#222",
                    "content-hover-bg": "#adadad",
                    "content-hover-fg": "#222"
                }
            }
        }
    },
    "pysssss.ModelInfo.CheckpointNodes": "CheckpointLoader.ckpt_name,CheckpointLoaderSimple,CheckpointLoader|pysssss,Efficient Loader,Eff. Loader SDXL,ttN pipeLoader_v2,ttN pipeLoaderSDXL_v2,ttN tinyLoader",
    "pysssss.ModelInfo.LoraNodes": "LoraLoader.lora_name,LoraLoader|pysssss,LoraLoaderModelOnly.lora_name,LoRA Stacker.lora_name.*,ttN KSampler_v2,ttN pipeKSampler_v2,ttN pipeKSamplerAdvanced_v2,ttN pipeKSamplerSDXL_v2",
    "Comfy.DevMode": true,
    "Comfy.Workflow.WorkflowTabsPosition": "Topbar (2nd-row)",
    "Comfy.Window.UnloadConfirmation": false,
    "Comfy.TutorialCompleted": true,
    "Comfy.Workflow.SortNodeIdOnSave": true,
    "Comfy.NodeBadge.NodeIdBadgeMode": "Show all",
    "Comfy.Sidebar.Size": "small",
    "Comfy.Sidebar.Location": "right",
    "Comfy.Keybinding.NewBindings": [
        {
            "commandId": "Comfy.ClearPendingTasks",
            "combo": {
                "key": "Enter",
                "ctrl": true,
                "alt": true,
                "shift": true
            }
        },
        {
            "commandId": "Workspace.ToggleSidebarTab.workflows",
            "combo": {
                "key": "m",
                "ctrl": false,
                "alt": true,
                "shift": false
            }
        },
        {
            "commandId": "Comfy.SaveWorkflowAs",
            "combo": {
                "key": "s",
                "ctrl": true,
                "alt": true,
                "shift": false
            }
        }
    ],
    "Comfy.Keybinding.UnsetBindings": [
        {
            "commandId": "Comfy.ClearWorkflow",
            "combo": {
                "key": "Backspace",
                "ctrl": false,
                "alt": false,
                "shift": false
            }
        },
        {
            "commandId": "Workspace.ToggleSidebarTab.queue",
            "combo": {
                "key": "q",
                "ctrl": false,
                "alt": false,
                "shift": false
            }
        },
        {
            "commandId": "Workspace.ToggleSidebarTab.node-library",
            "combo": {
                "key": "n",
                "ctrl": false,
                "alt": false,
                "shift": false
            }
        },
        {
            "commandId": "Workspace.ToggleSidebarTab.model-library",
            "combo": {
                "key": "m",
                "ctrl": false,
                "alt": false,
                "shift": false
            }
        },
        {
            "commandId": "Workspace.ToggleSidebarTab.workflows",
            "combo": {
                "key": "w",
                "ctrl": false,
                "alt": false,
                "shift": false
            }
        }
    ],
    "Comfy.DOMClippingEnabled": true,
    "Comfy.Node.ShowExperimental": true,
    "Comfy.LinkRelease.ActionShift": "no action",
    "Comfy.LinkRelease.Action": "context menu",
    "Comfy.NodeBadge.NodeSourceBadgeMode": "Show all",
    "Comfy.TreeExplorer.ItemPadding": 0,
    "Comfy.TextareaWidget.FontSize": 8,
    "pysssss.ShowImageOnMenu": false,
    "pysssss.Combo++.Submenu": true,
    "Crystools.ProgressBar": false,
    "Crystools.MonitorHeight": 31,
    "Crystools.RefreshRate": 1,
    "KJNodes.nodeAutoColor": false,
    "KJNodes.SetGetMenu": "top"
}

### What browsers do you use to access the UI ?

_No response_

### Other Information

Image

Image

Disabling caching and deleting db does not work

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-3498-Bug-useErrorHandling-ts-8-TypeError-crypto-randomUUID-is-not-a-function-1d96d73d3650810d933bd63b867dfff2) by [Unito](https://www.unito.io)

### LINKED ISSUE #7654: Cannot "Save As" existing workflow as new workflow
### Expected Behavior

Running ComfyUI latest version (updated last night) on Windows 11 in the self contained desktop app.  Attempting to save an existing workflow as a new workflow using "Save As" functionality.  Expected behavior is for it to save the workflow as a new workflow.

### Actual Behavior

I'm getting the following error when I attempt to do this:

"crypto.randomUUID is not a function"

Error also appears in the console.  Screenshot attached.

Image

### Steps to Reproduce

Steps to reproduce:

- Open up an existing workflow
- Go to the menu and select "Save As"
- Type in a new name for the workflow
- Click Save

### Debug Logs

```powershell
useErrorHandling.ts:8 TypeError: crypto.randomUUID is not a function
    at Object.saveWorkflowAs (workflowService.ts:98:25)
    at async function (useCoreCommands.ts:104:15)
    at async useErrorHandling.ts:40:16
    at async Proxy.execute (commandStore.ts:96:7)
toastErrorHandler	@	useErrorHandling.ts:8
(anonymous)	@	useErrorHandling.ts:42
await in (anonymous)		
execute	@	commandStore.ts:96
command	@	menuItemStore.ts:55
```

### Other

_No response_

### PR DESCRIPTION
**Pull request by huchenlei**
Resolves https://github.com/comfyanonymous/ComfyUI/issues/7654
Resolves https://github.com/Comfy-Org/ComfyUI_frontend/issues/3498

This PR uses guarded version of generateUUID for insecure context usage. Issue originally introduced in #3407

┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-3505-Bug-Fix-uuid-generation-in-insecure-context-1d96d73d36508119bc8ede66e20d4300) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by webfiltered** [comment]
Just noting: the impl. in litegraph (`createUuidv4`) works slightly differently; it falls back to `crypto.getRandomValues` rather than `Math.random`.  This is not likely to cause issues.
