### ISSUE TITLE
[Bug]: Pre-commit failing, property `trackEvent` doesn't exist

### ISSUE THREAD

**Issue by benceruleanlu** [Comfy-Org/ComfyUI_frontend#2273]
### Frontend Version

1.7.13

### Expected Behavior

For the pre-commit to not fail!

### Actual Behavior

The pre-commit failed on a change that I didn't make! The changes that `vue-tsc --noEmit` referenced were introduced in https://github.com/Comfy-Org/ComfyUI_frontend/commit/37abdbe35d5d6c0f56988b28359b877ae736bef0.

### Steps to Reproduce

Run git commit on any change, even a comment in a random place.

### Debug Logs

```powershell
✔ Preparing lint-staged...
⚠ Running tasks for staged files...
  ❯ lint-staged.config.js — 1 file
    ↓ ./**/*.js — no files
    ❯ ./**/*.{ts,tsx,vue,mts} — 1 file
      ✔ prettier --write C:/Users/benja/Code/ComfyUI_frontend/src/extensions/core/maskeditor.ts --plugin @trivago/prettier-plugin-sor…  
      ✔ eslint --fix C:/Users/benja/Code/ComfyUI_frontend/src/extensions/core/maskeditor.ts
      ✖ vue-tsc --noEmit [FAILED]
      ◼ tsc --noEmit
      ◼ tsc-strict
↓ Skipped because of errors from tasks.
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...

✖ vue-tsc --noEmit:
src/views/InstallView.vue(143,24): error TS2339: Property 'trackEvent' does not exist on type '{ readonly getDetectedGpu: () => Promise<GpuType>; readonly setWindowStyle: (style: "custom" | "default") => Promise<void>; readonly getWindowStyle: () => Promise<"custom" | "default">; }'.
src/views/InstallView.vue(182,24): error TS2339: Property 'trackEvent' does not exist on type '{ readonly getDetectedGpu: () => Promise<GpuType>; readonly setWindowStyle: (style: "custom" | "default") => Promise<void>; readonly getWindowStyle: () => Promise<"custom" | "default">; }'.
```

### Browser Logs

[localhost-1737079932106.log](https://github.com/user-attachments/files/18447483/localhost-1737079932106.log)

### Setting JSON

[comfy.settings.json](https://github.com/user-attachments/files/18447487/comfy.settings.json)

### What browsers do you use to access the UI ?

Google Chrome

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-2273-Bug-Pre-commit-failing-property-trackEvent-doesn-t-exist-17e6d73d3650813fa92ae43fce49b152) by [Unito](https://www.unito.io)

**Comment by benceruleanlu** [comment]
Running `npm install` does indeed fix it. Very funny!

**Comment by huchenlei** [comment]
This is caused by the electron types update recently. That library is only used for typing of electronAPI.
