### PR TITLE
[backport cloud/1.48] fix(workflow): build nodes for uninstalled types on API JSON import (#14555)

### PR DESCRIPTION
**Pull request by jaeone94**
Backport of #14555 to this branch. The automation could not do this one — see below.

## Why the auto-backport failed

The bot reported a cherry-pick conflict in `src/scripts/app.test.ts`. That is real but superficial: all three hunks are **import-block conflicts**, because this branch's `app.test.ts` has a much smaller import list than `main` (several PRs that touched that file were never backported here), so the diff context does not line up.

**The blocking problem was underneath, and only surfaced at typecheck:**

```
src/scripts/app.ts(2083,11): error TS2561: Object literal may only specify known properties,
but 'widgets_values_named' does not exist in type 'ISerialisedNode'.
```

`widgets_values_named` was introduced by #10392 ("Implement widgets_values_named for serialization"). It is present on `1.49` and `main`, and absent here:

| branch | `widgets_values_named` in `serialisation.ts` |
|---|---|
| core/1.48, cloud/1.48 | no |
| core/1.49, cloud/1.49 | yes |
| main | yes |

So a literal cherry-pick does not compile on `1.48` regardless of how the import conflict is resolved.

## Adjustments made

**1. Dropped `widgets_values_named` from the placeholder's `last_serialization`.** Not a behaviour loss on this branch: `LGraphNode.configure` here restores widget values positionally only —

```js
// core/1.48 — LGraphNode.ts:986
if (info.widgets_values) {
  ...
  widget.value = info.widgets_values[i++]
}
```

— with no named-restore path (`namedValuesRestore` and the `widgets_values_named` read arrive with #10392). The field would have been written and never read. The placeholder still carries its values positionally, its input slots, and its links, which is the substance of the fix.

**2. Resolved the three import conflicts by taking the incoming side**, which is a superset of what this branch had, then removed four imports whose consuming tests only exist on `main`: `setTelemetryRegistry`, `TelemetryRegistry`, `executionContextUtils`, `createNodeExecutionId`.

**3. Adapted two assertions** in the placeholder-serialization test from `widgets_values` + `widgets_values_named` to positional `widgets_values` only.

## Verification

`pnpm typecheck`, `pnpm typecheck:browser`, `pnpm format`, `pnpm lint` (0 errors) all pass. `src/scripts/app.test.ts` 42/42.

### CODE REVIEW

**Comment by benceruleanlu** [comment]
cloud/1.48 isn't shipping, cloud/1.49 is shipping today afternoon.
