### PR TITLE
billing: resolve the top-up deep link against server capabilities

### PR DESCRIPTION
**Pull request by wei-hai**
Moves the `?topup=` deep-link decision onto the server-resolved capabilities.

**Includes the initialization-race fix from review.** The loader awaits `initialize()` before reading `canTopUp` / `canSubscribeSelfServe`, so an eligible user no longer loses the deep link when the decision would otherwise be evaluated while both flags are still at their initial `false`. Its regression coverage is in the updated test alongside it.

Isolated so that fix and its test are reviewable without the migration diff around them.

Split out of #15641. Based on #15804.

### CODE REVIEW

**Comment by wei-hai** [comment]
Closing — folded into #15804.

The split put `useTopUpUrlLoader.ts` here, but #15804 removes `canTopUp` from `WorkspacePermissions`, and this file reads it. That made #15804 fail to typecheck on its own:

```
useTopUpUrlLoader.ts(58,28): error TS2339:
  Property 'canTopUp' does not exist on type 'WorkspacePermissions'
```

A PR that cannot build in isolation is worse than a slightly larger one, so the deep-link loader and its test now ride with the type change that requires them. The initialization-race fix and its regression test moved along with it.
